import { cn } from '@/lib/utils'

/** Auto-migrated from legacy CSS — Phase 7 Wave 6 */
export const dov = {
  allGapsSheetEmptyPool: 'm-[0 0 var(--space-3)] p-[var(--space-3)] text-[length:var(--text-caption)] [line-height:1.5] text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-surface, #fff) 92%, var(--color-border, #ccc) 8%)] [border:1px dashed var(--color-border)] [border-radius:6px] m-[0 0 var(--space-3)] p-[var(--space-3)] text-[length:var(--text-caption)] [line-height:1.5] text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-surface, #fff) 92%, var(--color-border, #ccc) 8%)] [border:1px dashed var(--color-border)] [border-radius:6px]',
  allGapsSheetGuide: 'm-[0 0 var(--space-4)] p-[var(--space-3)] bg-[color-mix(in srgb, var(--color-surface, #fff) 88%, var(--color-border, #ccc) 12%)] [border:1px solid var(--color-border)] [border-radius:6px] m-[0 0 var(--space-4)] p-[var(--space-3)] bg-[color-mix(in srgb, var(--color-surface, #fff) 88%, var(--color-border, #ccc) 12%)] [border:1px solid var(--color-border)] [border-radius:6px]',
  allGapsSheetGuideDl: 'm-0 flex flex-col gap-[var(--space-2)] text-[length:var(--text-caption)] [line-height:1.55] m-0 flex flex-col gap-[var(--space-2)] text-[length:var(--text-caption)] [line-height:1.55]',
  allGapsSheetGuideItem: 'm-0 p-[var(--space-2) var(--space-3)] [border-radius:6px] [border:1px solid color-mix(in srgb, var(--ocg-accent, var(--color-border)) 38%, var(--color-border))] [border-left:4px solid var(--ocg-accent, var(--color-border))] bg-[color-mix(in srgb, var(--color-surface, #fff) 90%, var(--ocg-accent, var(--color-border)) 10%)] m-0 p-[var(--space-2) var(--space-3)] [border-radius:6px] [border:1px solid color-mix(in srgb, var(--ocg-accent, var(--color-border)) 38%, var(--color-border))] [border-left:4px solid var(--ocg-accent, var(--color-border))] bg-[color-mix(in srgb, var(--color-surface, #fff) 90%, var(--ocg-accent, var(--color-border)) 10%)]',
  allGapsSheetGuideItemAudit: '[--ocg-accent:#64748b] [--ocg-accent:#64748b]',
  allGapsSheetGuideItemCoverage: '[--ocg-accent:#d97706] [--ocg-accent:#d97706]',
  allGapsSheetGuideItemIdentity: '[--ocg-accent:#3b82f6] [--ocg-accent:#3b82f6]',
  allGapsSheetGuideItemNullable: '[--ocg-accent:#db2777] [--ocg-accent:#db2777]',
  allGapsSheetGuideItemPk: '[--ocg-accent:#8b5cf6] [--ocg-accent:#8b5cf6]',
  allGapsSheetGuideItemVendor: '[--ocg-accent:#14b8a6] [--ocg-accent:#14b8a6]',
  allGapsSheetGuideNote: 'm-[var(--space-3) 0 0] [padding-top:var(--space-2)] [border-top:1px solid color-mix(in srgb, var(--color-border) 55%, transparent)] text-[length:var(--text-caption)] [line-height:1.45] text-[var(--color-text-muted)] m-[var(--space-3) 0 0] [padding-top:var(--space-2)] [border-top:1px solid color-mix(in srgb, var(--color-border) 55%, transparent)] text-[length:var(--text-caption)] [line-height:1.45] text-[var(--color-text-muted)]',
  allGapsSheetGuideTitle: 'm-[0 0 var(--space-2)] text-[length:var(--text-body)] font-semibold m-[0 0 var(--space-2)] text-[length:var(--text-body)] font-semibold',
  allGapsSheetQueriesLink: 'bg-none border-0 [padding:0.15rem 0] m-0 text-[length:var(--text-caption, 0.75rem)] text-[var(--color-primary, #5b7cff)] underline cursor-pointer whitespace-nowrap bg-none border-0 [padding:0.15rem 0] m-0 text-[length:var(--text-caption, 0.75rem)] text-[var(--color-primary, #5b7cff)] underline cursor-pointer whitespace-nowrap',
  allGapsSheetSym: 'p-[var(--space-3) 0] [border-bottom:1px solid var(--color-border)] p-[var(--space-3) 0] [border-bottom:1px solid var(--color-border)]',
  allGapsSheetSymH: 'm-[0 0 var(--space-2)] text-[length:var(--text-body)] m-[0 0 var(--space-2)] text-[length:var(--text-body)]',
  allGapsSheetTruncBanner: 'mb-[var(--space-3)] mb-[var(--space-3)]',
  barsGapQueriesBlockHead: 'flex items-center justify-between gap-[var(--space-2)] mb-[var(--space-1)] flex items-center justify-between gap-[var(--space-2)] mb-[var(--space-1)]',
  barsGapQueriesBlockLabel: 'text-[length:var(--text-caption)] font-semibold text-[var(--color-text)] text-[length:var(--text-caption)] font-semibold text-[var(--color-text)]',
  barsGapQueriesBody: 'flex flex-col gap-[var(--space-3)] flex flex-col gap-[var(--space-3)]',
  barsGapQueriesLead: 'm-[0 0 var(--space-1)] text-[length:var(--text-caption)] text-[var(--color-text-muted)] [line-height:1.45] m-[0 0 var(--space-1)] text-[length:var(--text-caption)] text-[var(--color-text-muted)] [line-height:1.45]',
  barsGapQueriesMeta: 'mb-[var(--space-2)] mb-[var(--space-2)]',
  barsGapQueriesPre: 'm-0 p-[var(--space-2) var(--space-3)] [font-size:0.6875rem] [line-height:1.45] overflow-x-auto [max-height:14rem] overflow-y-auto bg-[color-mix(in srgb, var(--color-surface, #fff) 90%, var(--color-border, #ccc) 10%)] [border:1px solid var(--color-border)] rounded-[var(--radius-sm, 4px)] [white-space:pre-wrap] break-all m-0 p-[var(--space-2) var(--space-3)] [font-size:0.6875rem] [line-height:1.45] overflow-x-auto [max-height:14rem] overflow-y-auto bg-[color-mix(in srgb, var(--color-surface, #fff) 90%, var(--color-border, #ccc) 10%)] [border:1px solid var(--color-border)] rounded-[var(--radius-sm, 4px)] [white-space:pre-wrap] break-all',
  checkRunPill: 'text-[length:var(--font-size-sm)] font-semibold text-[var(--color-accent)] [padding:0.2rem 0.55rem] [border-radius:999px] [border:1px solid color-mix(in srgb, var(--color-accent) 45%, var(--color-border))] bg-[color-mix(in srgb, var(--color-accent) 12%, transparent)] cursor-pointer [font-family:inherit] text-[length:var(--font-size-sm)] font-semibold text-[var(--color-accent)] [padding:0.2rem 0.55rem] [border-radius:999px] [border:1px solid color-mix(in srgb, var(--color-accent) 45%, var(--color-border))] bg-[color-mix(in srgb, var(--color-accent) 12%, transparent)] cursor-pointer [font-family:inherit]',
  contractsPanel: 'flex flex-col [gap:0.55rem] flex flex-col [gap:0.55rem]',
  contractsPanelConclusion: 'mt-[var(--space-2)] [border-radius:6px] [border:1px solid var(--color-border)] bg-[rgba(0, 0, 0, 0.12)] mt-[var(--space-2)] [border-radius:6px] [border:1px solid var(--color-border)] bg-[rgba(0, 0, 0, 0.12)] bg-[rgba(0, 0, 0, 0.02)]',
  contractsPanelConclusionBody: 'p-[0 var(--space-2) var(--space-2)] [border-top:1px solid var(--color-border)] p-[0 var(--space-2) var(--space-2)] [border-top:1px solid var(--color-border)]',
  contractsPanelConclusionSum: '[padding:0.4rem 0.65rem] text-[length:var(--text-caption)] font-semibold text-[var(--color-text-muted)] cursor-pointer list-none [padding:0.4rem 0.65rem] text-[length:var(--text-caption)] font-semibold text-[var(--color-text-muted)] cursor-pointer list-none',
  contractsPanelEm: 'text-[#7dd3fc] font-semibold text-[#7dd3fc] font-semibold text-[#0369a1]',
  contractsPanelGapScope: 'inline-flex items-center [gap:0.15rem] inline-flex items-center [gap:0.15rem]',
  contractsPanelGate: 'm-0 text-[length:var(--text-tiny)] text-[#fbbf24] m-0 text-[length:var(--text-tiny)] text-[#fbbf24]',
  contractsPanelGroupActions: 'inline-flex flex-wrap items-center [gap:0.4rem] inline-flex flex-wrap items-center [gap:0.4rem]',
  contractsPanelGroupCount: '[min-width:1.1rem] text-[length:var(--text-caption)] font-bold tabular-nums [line-height:1.2] text-[var(--color-text, #e5e7eb)] [min-width:1.1rem] text-[length:var(--text-caption)] font-bold tabular-nums [line-height:1.2] text-[var(--color-text, #e5e7eb)]',
  contractsPanelGroupHead: 'inline-flex items-baseline [gap:0.35rem] inline-flex items-baseline [gap:0.35rem]',
  contractsPanelGroupKicker: '[font-size:0.65rem] font-bold [letter-spacing:0.06em] uppercase text-[var(--color-text-muted)] whitespace-nowrap [font-size:0.65rem] font-bold [letter-spacing:0.06em] uppercase text-[var(--color-text-muted)] whitespace-nowrap',
  contractsPanelGuide: '[padding:0.45rem 0.55rem] [border-radius:6px] bg-[rgba(0, 0, 0, 0.14)] [border:1px solid rgba(255, 255, 255, 0.06)] [padding:0.45rem 0.55rem] [border-radius:6px] bg-[rgba(0, 0, 0, 0.14)] [border:1px solid rgba(255, 255, 255, 0.06)] bg-[rgba(0, 0, 0, 0.04)] border-[rgba(0, 0, 0, 0.08)]',
  contractsPanelGuideText: 'm-0 text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)] m-0 text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)]',
  contractsPanelPool: 'inline-flex flex-wrap items-center [gap:0.45rem] inline-flex flex-wrap items-center [gap:0.45rem]',
  contractsPanelSummary: '[min-height:1.35em] [min-height:1.35em]',
  contractsPanelToolbar: 'flex flex-wrap items-center [gap:0.5rem] w-full flex flex-wrap items-center [gap:0.5rem] w-full',
  contractsPanelToolbarLeft: 'flex flex-wrap items-center [gap:0.5rem] min-w-0 [flex:1 1 auto] flex flex-wrap items-center [gap:0.5rem] min-w-0 [flex:1 1 auto]',
  contractsPanelToolbarRight: 'flex flex-wrap items-center [gap:0.4rem] [margin-left:auto] flex flex-wrap items-center [gap:0.4rem] [margin-left:auto]',
  ctl: 'inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[length:var(--text-tiny)] font-semibold cursor-pointer',
  ctlCheck: 'border-[rgba(56, 189, 248, 0.55)] bg-[rgba(14, 165, 233, 0.14)] text-[#7dd3fc] border-[rgba(56, 189, 248, 0.55)] bg-[rgba(14, 165, 233, 0.14)] text-[#7dd3fc] border-[#38bdf8] bg-[rgba(14, 165, 233, 0.1)] text-[#0369a1]',
  ctlFill: 'border-[rgba(52, 211, 153, 0.55)] bg-[rgba(16, 185, 129, 0.2)] text-[#6ee7b7] border-[rgba(52, 211, 153, 0.55)] bg-[rgba(16, 185, 129, 0.2)] text-[#6ee7b7] border-[#34d399] bg-[rgba(16, 185, 129, 0.12)] text-[#047857]',
  ctlPlain: 'border-[rgba(255, 255, 255, 0.1)] bg-[rgba(0, 0, 0, 0.08)] text-[var(--color-text-muted)] font-medium border-[rgba(255, 255, 255, 0.1)] bg-[rgba(0, 0, 0, 0.08)] text-[var(--color-text-muted)] font-medium border-[rgba(0, 0, 0, 0.12)] bg-[rgba(0, 0, 0, 0.04)] text-[var(--color-text-muted)]',
  ctlIco: 'shrink-0 block shrink-0 block',
  focusChipsCompact: '[padding:0.46rem 0.52rem 0.52rem] [padding:0.46rem 0.52rem 0.52rem]',
  focusChipsChip: 'inline-flex items-center [gap:0.35rem] [padding:0.24rem 0.52rem] [border:1px solid var(--color-border, #2a313c)] [border-radius:999px] [font-size:0.8125rem] [line-height:1.3] text-[var(--color-text-main, #e4e9ef)] bg-[rgba(0, 0, 0, 0.18)] [border-radius:6px] [padding:0.26rem 0.55rem] [font-size:0.875rem] [gap:0] border-[var(--color-border-strong, #3d4754)] [outline:2px solid var(--color-link, #6b9bd4)] [outline-offset:1px] inline-flex items-center [gap:0.35rem] [padding:0.24rem 0.52rem] [border:1px solid var(--color-border, #2a313c)] [border-radius:999px] [font-size:0.8125rem] [line-height:1.3] text-[var(--color-text-main, #e4e9ef)] bg-[rgba(0, 0, 0, 0.18)] bg-[var(--color-surface-elevated, #1a1f26)] border-[var(--color-link, #6b9bd4)] shadow-[0 0 0 1px rgba(107, 155, 212, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.04)] bg-[rgba(0, 0, 0, 0.04)]',
  focusChipsChipCode: '[font-family:var(--font-mono, ui-monospace, monospace)] [font-size:0.78rem] font-medium [border-radius:5px] [letter-spacing:-0.02em] break-words [font-family:var(--font-mono, ui-monospace, monospace)] [font-size:0.78rem] font-medium [border-radius:5px] [letter-spacing:-0.02em] break-words',
  focusChipsChipPlaceholder: '[opacity:0.58] border-[var(--color-border, #2a313c)] bg-[rgba(0, 0, 0, 0.18)] [opacity:0.58]',
  focusChipsChipGroup: 'inline-flex flex-wrap items-center [gap:0.28rem 0.38rem] [padding:0.16rem 0.4rem] [border-radius:7px] bg-[rgba(0, 0, 0, 0.2)] [border:1px solid rgba(255, 255, 255, 0.055)] shadow-[inset 0 1px 0 rgba(255, 255, 255, 0.035)] inline-flex flex-wrap items-center [gap:0.28rem 0.38rem] [padding:0.16rem 0.4rem] [border-radius:7px] bg-[rgba(0, 0, 0, 0.2)] [border:1px solid rgba(255, 255, 255, 0.055)] shadow-[inset 0 1px 0 rgba(255, 255, 255, 0.035)] bg-[rgba(0, 0, 0, 0.04)] border-[rgba(0, 0, 0, 0.07)] shadow-[inset 0 1px 0 rgba(255, 255, 255, 0.65)]',
  focusChipsChipLabel: 'min-w-0 min-w-0',
  focusChipsChipWrap: 'relative inline-flex cursor-pointer [max-width:100%] relative inline-flex cursor-pointer [max-width:100%]',
  focusChipsChipWrapPlaceholder: '[cursor:help] [cursor:help]',
  focusChipsIcon: 'shrink-0 shrink-0',
  focusChipsIconTable: 'text-[var(--color-text-muted, #8b95a3)] text-[var(--color-text-muted, #8b95a3)]',
  focusChipsIconView: 'text-[#6ec8d8] text-[#6ec8d8] text-[#2a8fa0]',
  focusChipsLegend: '[float:none] w-full [margin:0 0 0.35rem] p-0 text-[length:var(--text-caption)] font-semibold text-[var(--color-text-main, #e4e9ef)] [line-height:1.35] [float:none] w-full [margin:0 0 0.35rem] p-0 text-[length:var(--text-caption)] font-semibold text-[var(--color-text-main, #e4e9ef)] [line-height:1.35]',
  focusChipsLegendText: 'inline-flex items-center [gap:0.2rem] flex-wrap inline-flex items-center [gap:0.2rem] flex-wrap',
  focusChipsMatrix: 'grid [grid-template-columns:auto minmax(0, 1fr)] [column-gap:0.4rem] [row-gap:0.18rem] items-center grid [grid-template-columns:auto minmax(0, 1fr)] [column-gap:0.4rem] [row-gap:0.18rem] items-center',
  focusChipsRk: '[font-size:0.72rem] font-semibold [line-height:1.25] uppercase [letter-spacing:0.04em] text-[var(--color-text-dim, #6b7582)] whitespace-nowrap [justify-self:end] [padding-right:0.05rem] [font-size:0.72rem] font-semibold [line-height:1.25] uppercase [letter-spacing:0.04em] text-[var(--color-text-dim, #6b7582)] whitespace-nowrap [justify-self:end] [padding-right:0.05rem]',
  focusChipsRow: 'flex flex-wrap items-center [gap:0.28rem 0.38rem] flex flex-wrap items-center [gap:0.28rem 0.38rem]',
  gapExplainSheet: '[width:min(38rem, 100vw)] [width:min(38rem, 100vw)]',
  gapExplainSheetBody: 'text-[length:var(--font-size-sm)] [line-height:1.5] text-[var(--color-text)] text-[length:var(--font-size-sm)] [line-height:1.5] text-[var(--color-text)]',
  gapExplainSheetH: 'm-[var(--space-3) 0 var(--space-1)] text-[length:var(--text-caption)] font-semibold [letter-spacing:0.02em] uppercase text-[var(--color-text-muted)] m-[var(--space-3) 0 var(--space-1)] text-[length:var(--text-caption)] font-semibold [letter-spacing:0.02em] uppercase text-[var(--color-text-muted)]',
  gapExplainSheetLead: 'm-[0 0 var(--space-3)] m-[0 0 var(--space-3)]',
  gapExplainSheetP: 'm-[0 0 var(--space-2)] text-[var(--color-text)] m-[0 0 var(--space-2)] text-[var(--color-text)]',
  gapSheet: 'p-[var(--space-3)] text-left p-[var(--space-3)] text-left',
  gapSheetEmbedded: 'p-0 mt-[var(--space-1)] p-0 mt-[var(--space-1)]',
  gapSheetColFillBtn: 'text-[length:var(--text-tiny)] [padding:0.15rem 0.4rem] whitespace-nowrap text-[length:var(--text-tiny)] [padding:0.15rem 0.4rem] whitespace-nowrap',
  gapSheetDash: 'text-[var(--color-text-muted)] text-[var(--color-text-muted)]',
  gapSheetErr: 'm-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-danger)] m-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-danger)]',
  gapSheetMetric: 'tabular-nums font-semibold tabular-nums',
  gapSheetMetricBad: 'text-[var(--color-danger)] font-semibold text-[var(--color-danger)] font-semibold',
  gapSheetMetricNa: 'text-[var(--color-text-muted)] font-medium text-[var(--color-text-muted)] font-medium',
  gapSheetMetricOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  gapSheetMetricWarn: 'text-[var(--color-warning)] font-semibold text-[var(--color-warning)] font-semibold',
  gapSheetNote: 'm-[0 0 var(--space-2)] text-[length:var(--text-tiny)] text-[var(--color-text-muted)] m-[0 0 var(--space-2)] text-[length:var(--text-tiny)] text-[var(--color-text-muted)]',
  gapSheetNullableLead: 'm-[0 0 var(--space-2)] text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)] m-[0 0 var(--space-2)] text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)]',
  gapSheetNullableLegend: 'm-[var(--space-2) 0 0] text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)] m-[var(--space-2) 0 0] text-[length:var(--text-tiny)] [line-height:1.45] text-[var(--color-text-muted)]',
  gapSheetNullableMeta: 'm-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-text)] m-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-text)]',
  gapSheetRefgapIntro: 'm-[0 0 var(--space-2)] text-[length:var(--text-caption)] [line-height:1.45] text-[var(--color-text-muted)] m-[0 0 var(--space-2)] text-[length:var(--text-caption)] [line-height:1.45] text-[var(--color-text-muted)]',
  gapSheetScope: 'm-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-text)] [line-height:1.45] m-[0 0 var(--space-2)] text-[length:var(--text-caption)] text-[var(--color-text)] [line-height:1.45]',
  gapSheetSec: 'mt-[var(--space-3)] mt-[var(--space-3)]',
  gapSheetSecHead: 'flex flex-wrap items-center justify-between gap-[var(--space-2)] mb-[var(--space-2)] flex flex-wrap items-center justify-between gap-[var(--space-2)] mb-[var(--space-2)]',
  gapSheetSecTitle: 'm-0 text-[length:var(--text-caption)] font-semibold [letter-spacing:0.02em] uppercase text-[var(--color-text-muted)] m-0 text-[length:var(--text-caption)] font-semibold [letter-spacing:0.02em] uppercase text-[var(--color-text-muted)]',
  gapSheetSecTitleSub: 'text-[length:var(--text-tiny)] normal-case [letter-spacing:normal] font-semibold text-[length:var(--text-tiny)] normal-case [letter-spacing:normal] font-semibold',
  gapSheetTbl: 'w-full border-collapse text-[length:var(--text-caption)] w-full border-collapse text-[length:var(--text-caption)]',
  gapSheetTblCompact: 'tabular-nums tabular-nums',
  gapSheetTrunc: 'text-[var(--color-warning)] font-bold text-[var(--color-warning)] font-bold',
  optionJobsBarActions: 'inline-flex flex-wrap items-center [gap:0.4rem] inline-flex flex-wrap items-center [gap:0.4rem]',
  optionJobsBarHint: '[margin:0.45rem 0 0] text-[length:var(--text-tiny)] text-[var(--color-text-muted)] [line-height:1.4] [margin:0.45rem 0 0] text-[length:var(--text-tiny)] text-[var(--color-text-muted)] [line-height:1.4]',
  optionJobsBarHintErr: 'text-[var(--color-danger, #f87171)] text-[var(--color-danger, #f87171)]',
  optionJobsBarPool: 'inline-flex flex-wrap items-center [gap:0.4rem] text-[length:var(--text-caption)] text-[var(--color-text-muted)] inline-flex flex-wrap items-center [gap:0.4rem] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  optionJobsBarPoolLabel: 'font-semibold whitespace-nowrap font-semibold whitespace-nowrap',
  optionJobsBarRow: 'flex flex-wrap items-center justify-between gap-[var(--space-2)] flex flex-wrap items-center justify-between gap-[var(--space-2)]',
  optionJobsBarSym: 'inline-flex items-center [gap:0.4rem] text-[length:var(--text-caption)] text-[var(--color-text-muted)] inline-flex items-center [gap:0.4rem] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  optionJobsBarSymLabel: 'whitespace-nowrap whitespace-nowrap',
  optionJobsBarSymSelect: '[min-width:6rem] [max-width:10rem] text-[length:var(--text-caption)] [padding:0.2rem 0.45rem] [min-width:6rem] [max-width:10rem] text-[length:var(--text-caption)] [padding:0.2rem 0.45rem]',
  refStrip: 'mt-[var(--space-2)] [padding-top:var(--space-2)] [border-top:1px solid rgba(255, 255, 255, 0.06)] mt-[var(--space-2)] [padding-top:var(--space-2)] [border-top:1px solid rgba(255, 255, 255, 0.06)] [border-top-color:rgba(0, 0, 0, 0.08)]',
  refStripCompareBtns: 'inline-flex flex-wrap [gap:0.4rem] shrink-0 inline-flex flex-wrap [gap:0.4rem] shrink-0',
  refStripCovPct: 'tabular-nums tabular-nums',
  refStripCovPctOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  refStripCovPctWarn: 'text-[var(--color-danger)] font-bold text-[var(--color-danger)] font-bold',
  refStripGapNum: 'tabular-nums tabular-nums',
  refStripGapNumOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  refStripGapNumWarn: 'text-[var(--color-danger)] font-bold text-[var(--color-danger)] font-bold',
  refStripGate: '[margin:0.35rem 0 0] text-[length:var(--text-tiny)] text-[var(--color-text-muted)] [margin:0.35rem 0 0] text-[length:var(--text-tiny)] text-[var(--color-text-muted)]',
  refStripMeta: 'text-[length:var(--text-caption)] text-[var(--color-text-muted)] [line-height:1.35] text-[length:var(--text-caption)] text-[var(--color-text-muted)] [line-height:1.35]',
  refStripMetaMuted: '[opacity:0.92] text-[length:var(--text-tiny)] [opacity:0.92] text-[length:var(--text-tiny)]',
  refStripRow: 'flex flex-wrap items-center [gap:0.65rem] flex flex-wrap items-center [gap:0.65rem]',
  refStripRowCompare: 'items-start items-start',
  refStripTime: 'text-[length:var(--text-tiny)] [opacity:0.88] text-[length:var(--text-tiny)] [opacity:0.88]',
  wlMatrixCompletenessPctBad: 'text-[var(--color-danger)] font-bold text-[var(--color-danger)] font-bold',
  wlMatrixCompletenessPctOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  wlMatrixCompletenessPctWarn: 'text-[var(--color-warning)] font-semibold text-[var(--color-warning)] font-semibold',
  wlMatrixCompletenessSep: 'text-[var(--color-text-muted)] font-medium text-[var(--color-text-muted)] font-medium',
  wlMatrixCovpct: 'tabular-nums tabular-nums',
  wlMatrixCovpctOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  wlMatrixCovpctWarn: 'text-[var(--color-danger)] font-bold text-[var(--color-danger)] font-bold',
  wlMatrixGapMmSep: 'text-[var(--color-text-muted)] font-medium [padding:0 0.12em] text-[var(--color-text-muted)] font-medium [padding:0 0.12em]',
  wlMatrixGapnum: 'tabular-nums tabular-nums',
  wlMatrixGapnumOk: 'text-[var(--color-success)] font-semibold text-[var(--color-success)] font-semibold',
  wlMatrixGapnumWarn: 'text-[var(--color-danger)] font-bold text-[var(--color-danger)] font-bold',
  wlMatrixRefcell: 'text-[length:var(--text-caption)] tabular-nums whitespace-nowrap text-[length:var(--text-caption)] tabular-nums whitespace-nowrap',
  wlMatrixSymBtn: 'appearance-none border-0 [background:transparent] [padding:0.1rem 0.2rem] m-0 font-[inherit] font-bold text-[var(--color-text)] cursor-pointer text-left [border-radius:4px] appearance-none border-0 [background:transparent] [padding:0.1rem 0.2rem] m-0 font-[inherit] font-bold text-[var(--color-text)] cursor-pointer text-left [border-radius:4px]',
  wlMatrixSymBtnOn: 'text-[#38bdf8] text-[#38bdf8] text-[#0369a1]',
  wlMatrixSymDetailBtn: 'appearance-none border-0 [background:transparent] [padding:0 0.15rem] [margin:0 0 0 0.1rem] [font-size:0.7rem] [line-height:1] text-[var(--color-muted, #64748b)] cursor-pointer [border-radius:3px] align-middle [opacity:0.6] appearance-none border-0 [background:transparent] [padding:0 0.15rem] [margin:0 0 0 0.1rem] [font-size:0.7rem] [line-height:1] text-[var(--color-muted, #64748b)] cursor-pointer [border-radius:3px] align-middle [opacity:0.6]',
} as const

export function dovCn(...parts: Array<string | false | null | undefined>) {
  return cn(...parts)
}
