import { cn } from '@/lib/utils'

/** Auto-migrated from sip-*.css — Phase 7 Wave 4 */
export const SIP = {
  chainFresh: 'font-bold rounded-[3px]',
  chainFreshOk: 'font-bold rounded-[3px]',
  chainFreshStale: 'font-bold rounded-[3px]',
  chainFreshWarn: 'font-bold rounded-[3px]',
  chainHeader: 'flex select-none',
  chainHeaderMeta: 'flex gap-2',
  chainRow: '',
  chainRowTotal: '',
  chainScroll: '',
  chainSection: '[margin-top:6px]',
  chainSharedRefresh: 'text-muted-foreground opacity-75',
  chainTable: 'w-full border-collapse tabular-nums',
  chainTd: 'text-muted-foreground',
  chainTdBearish: 'text-muted-foreground font-semibold',
  chainTdBullish: 'text-muted-foreground font-semibold',
  chainTdCall: 'text-muted-foreground',
  chainTdDte: 'font-bold text-muted-foreground',
  chainTdExp: 'text-muted-foreground font-semibold',
  chainTdNum: 'text-muted-foreground',
  chainTdPut: 'text-muted-foreground',
  chainTh: 'font-bold uppercase',
  chainThCall: 'font-bold uppercase',
  chainThNum: 'font-bold uppercase',
  chainThPut: 'font-bold uppercase',
  chainTitle: 'font-bold uppercase text-muted-foreground [padding-left:6px]',
  chartLegend: 'flex gap-2.5 text-muted-foreground [margin-bottom:4px]',
  condActual: 'text-muted-foreground font-semibold',
  condChevron: 'text-muted-foreground',
  condIcon: 'inline-flex rounded-[999px] font-bold',
  condLabel: 'text-muted-foreground min-w-0',
  condList: 'list-none m-0 p-0 flex',
  condListExt: 'm-0',
  condMetric: 'text-muted-foreground',
  condPill: 'inline-flex font-bold rounded-[3px]',
  condPillFail: 'text-muted-foreground',
  condPillPass: 'text-muted-foreground',
  condRow: 'grid',
  condRowPass: 'grid',
  condRowFail: 'grid',
  condRowActive: 'rounded-[4px]',
  condRowClickable: 'rounded-[4px]',
  condRowNeutral: 'grid',
  condThreshold: 'text-muted-foreground',
  condVs: 'text-muted-foreground',
  conditionsGrid: 'grid items-stretch',
  extGroup: 'border border-border rounded-[6px]',
  extGroupBadge: 'font-bold rounded-[8px]',
  extGroupBadgeFail: 'font-bold rounded-[8px]',
  extGroupBadgeInsuf: 'font-bold rounded-[8px]',
  extGroupBadgePass: 'font-bold rounded-[8px]',
  extGroupHeader: 'flex font-semibold select-none',
  extGroupLabel: 'text-muted-foreground',
  extGroups: '[margin-top:10px] flex gap-1',
  fundAsof: 'font-medium text-muted-foreground',
  fundCallout: 'rounded-[6px]',
  fundCalloutWarn: 'text-muted-foreground',
  fundHint: 'text-muted-foreground m-0',
  fundHintErr: 'text-muted-foreground',
  fundSection: '',
  fundSummary: 'flex gap-2 [margin-top:0.65re] rounded-[6px] font-semibold',
  fundSummaryOk: 'text-muted-foreground',
  fundSummaryWarn: 'text-muted-foreground border border-border',
  fundSummaryLabel: 'uppercase opacity-85',
  fundSummaryValue: 'font-bold',
  fundTitle: 'flex items-baseline gap-2',
  legendDot: 'inline-block rounded-[2px] shrink-0',
  legendDotRef: 'inline-block',
  miniBar: 'absolute rounded-[2px]',
  miniBarCell: 'relative [padding-bottom:5px]',
  overviewChip: 'inline-flex rounded-[10px] font-semibold border border-border text-muted-foreground',
  overviewChipDim: 'text-muted-foreground',
  overviewChipExch: 'inline-flex rounded-[10px] font-semibold border border-border text-muted-foreground',
  overviewChipLink: 'text-muted-foreground',
  overviewChipNum: 'inline-flex rounded-[10px] font-semibold border border-border text-muted-foreground',
  overviewChipSector: 'inline-flex rounded-[10px] font-semibold border border-border text-muted-foreground',
  overviewDesc: 'text-muted-foreground m-0',
  overviewDescExpanded: 'block',
  overviewDescWrap: '[margin-bottom:8px]',
  overviewMetaRow: 'flex gap-1.5 [margin-bottom:8px]',
  overviewName: 'font-bold text-muted-foreground [margin-right:4px] shrink-0',
  overviewRelated: 'flex [padding-top:6px]',
  overviewRelatedChip: 'inline-flex rounded-[8px] font-semibold border border-border text-muted-foreground',
  overviewRelatedLabel: 'font-bold uppercase text-muted-foreground [margin-right:2px] shrink-0',
  overviewRelatedNone: 'text-muted-foreground',
  overviewSection: '',
  passBadge: 'inline-flex [margin-left:0.5re] rounded-[12px] font-bold',
  passBadgeFull: 'text-muted-foreground',
  passBadgePartial: 'text-muted-foreground',
  passBadgePoor: 'text-muted-foreground',
  passBadgeUnknown: 'text-muted-foreground border border-border',
  pcrActionBtn: 'rounded-[4px] border border-border bg-card text-muted-foreground',
  pcrActionBtnPrimary: 'rounded-[4px] border border-border bg-card text-muted-foreground',
  pcrBgBanner: 'rounded-[6px] flex gap-1.5',
  pcrBgBannerRow: 'flex gap-1.5',
  pcrBgLabel: 'text-muted-foreground flex-1 min-w-0',
  pcrBgProgress: 'flex gap-1',
  pcrBgSpinner: 'inline-block rounded-full shrink-0',
  pcrBgStage: 'font-semibold',
  pcrBgStats: 'flex gap-1 text-muted-foreground tabular-nums opacity-85',
  pcrBlock: '',
  pcrCellBearish: 'text-muted-foreground',
  pcrCellBullish: 'text-muted-foreground',
  pcrFirstFetch: '',
  pcrHint: 'text-muted-foreground',
  pcrLabel: 'text-muted-foreground uppercase',
  pcrMetric: 'flex',
  pcrMetrics: 'flex gap-3 [margin-bottom:6px]',
  pcrProgressBarFill: 'rounded-[4px]',
  pcrProgressBarTrack: 'rounded-[4px]',
  pcrProgressJobid: 'opacity-[0.5]',
  pcrProgressPcr: 'font-semibold',
  pcrRefreshAsof: 'inline-flex text-muted-foreground',
  pcrRefreshBtn: 'inline-flex gap-2 rounded-[4px] border border-border text-muted-foreground',
  pcrRefreshLabel: 'font-bold uppercase text-muted-foreground [padding-left:6px]',
  pcrRetrieveBlock: 'flex gap-2',
  pcrSectionHead: 'flex',
  pcrSectionHeadActions: 'inline-flex gap-2',
  pcrTabBtn: 'font-semibold rounded-[4px] border border-border bg-card text-muted-foreground',
  pcrTablesBody: '',
  pcrTablesGrid: 'grid gap-2.5',
  pcrTablesToggle: 'flex gap-2',
  pcrValue: 'font-semibold tabular-nums text-muted-foreground',
  pcrValueBearish: 'text-muted-foreground',
  pcrValueBullish: 'text-muted-foreground',
  rawActiveLabel: 'text-muted-foreground inline-flex',
  rawCellHighlight: 'font-bold text-muted-foreground rounded-[3px]',
  rawColBadge: 'inline-flex rounded-[3px] font-bold',
  rawHint: 'text-muted-foreground',
  rawPeriod: 'text-muted-foreground',
  rawRowHit: '',
  rawSection: '',
  rawTable: 'w-full border-collapse',
  rawTableLabel: 'font-bold uppercase text-muted-foreground [margin-bottom:4px]',
  rawThActive: 'text-muted-foreground',
  rawTitle: 'flex items-baseline',
  stmtBlockHead: 'flex gap-2 [margin-bottom:4px]',
  stmtChartCol: 'min-w-0',
  stmtChartTable: 'grid [margin-bottom:0.25re]',
  stmtCompactTable: 'w-full border-collapse',
  stmtTableCol: 'min-w-0',
  stmtsBlock: '[margin-bottom:var(--space-3)]',
  stmtsBlockTitle: 'font-bold uppercase text-muted-foreground [margin-bottom:4px] [padding-left:0] [padding-left:6px]',
  stmtsNeg: 'text-muted-foreground',
  stmtsPos: 'text-muted-foreground',
  stmtsScroll: '',
  stmtsSection: '',
  stmtsTable: '',
  stmtsToggle: 'select-none flex',
  stmtsToggleArrow: 'text-muted-foreground [margin-left:6px]',
  tierBadge: 'font-medium rounded-[6px] text-muted-foreground',
  tierDetails: '[margin-top:8px] border border-border rounded-[6px]',
  tierList: 'm-0',
  tierMetricRow: 'flex text-muted-foreground',
  tierScore: 'font-bold rounded-[8px]',
  tierSummary: 'flex font-semibold select-none text-muted-foreground bg-card',
  sipTimestamp: '',
} as const

/** Lookup with optional variant suffix e.g. `--ok` */
export function sip(base: string, variant?: string) {
  const key = camel_case(base.replace(/^^sip-/, "") + (variant ? `--${variant}` : ""))
  return (SIP as Record<string, string>)[key] ?? ""
}

function camel_case(s: string): string {
  const parts = s.split(/[-_]/)
  return parts[0] + parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("")
}

export function sipcn(base: string, variant?: string, extra?: string) {
  return cn(sip(base, variant), extra)
}
