import { cn } from '@/lib/utils'

/** Auto-migrated from app-surfaces.css — Phase 7 Wave 9 (final) */
export const w9 = {
  accountsPageHeaderIconWrap: 'inline-flex align-middle',
  accountSyncHbIntervalHint: '[opacity:0.75] font-medium [font-size:0.8rem]',
  appPageStack: 'flex flex-col',
  appSubmenuIcon: 'shrink-0 [width:1rem] [height:1rem] [opacity:0.85]',
  appTabIcon: 'shrink-0 [margin-right:var(--space-1)]',
  attrMixed: 'bg-[rgba(251, 191, 36, 0.16)] text-[#fbbf24]',
  attrSingle: 'bg-[rgba(34, 197, 94, 0.13)] text-[#22c55e]',
  attrUnassigned: 'bg-[rgba(148, 163, 184, 0.1)] text-[#64748b]',
  cardOperations: 'mb-[var(--space-2)]',
  countdownLine: 'mt-[var(--space-1)]',
  countdownNum: '[display:inline-block] [font-family:var(--font-mono)] text-[length:var(--text-caption)] [/* 与模块内文字保持一致 */ font-weight:600] tabular-nums text-[var(--color-accent)] [text-shadow:0 0 6px var(--color-accent-glow)]',
  coverageAccountHost: 'text-[#5eead4]',
  coverageAccountId: '[font-family:var(--font-mono, \'JetBrains Mono\', monospace)] [font-size:0.82em] font-semibold',
  coverageAccountSecondary: 'text-[#c4b5fd]',
  coverageAssetPieBody: 'flex flex-row items-start [gap:1rem 1.25rem] flex-wrap',
  coverageAssetPieBpLabel: '[font-size:0.74rem] font-semibold text-[var(--color-text-muted, #7a8492)] [line-height:1.25]',
  coverageAssetPieBpSide: 'flex flex-col items-start justify-center [gap:0.35rem] [max-width:11rem] [min-height:8.5rem]',
  coverageAssetPieBubbleSwitch: 'inline-flex items-center shrink-0 [padding:3px] [border-radius:999px] bg-[var(--color-surface, #13171d)] [border:1px solid var(--color-border, #2a313c)] [gap:2px]',
  coverageAssetPieCenterSub: '[font-size:0.52rem] font-medium [fill:var(--color-text-dim, #5c6572)] uppercase [letter-spacing:0.04em]',
  coverageAssetPieChartBlock: 'flex flex-row items-center [gap:0.65rem 1rem] shrink-0',
  coverageAssetPieChartToggleRow: 'flex flex-col items-start [gap:0.2rem] w-full',
  coverageAssetPieDot: '[width:8px] [height:8px] [border-radius:50%]',
  coverageAssetPieDotBp: 'bg-[var(--coverage-pie-bp)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieDotCash: 'bg-[var(--coverage-pie-cash)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieDotCashlike: 'bg-[var(--coverage-pie-cashlike)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieDotFi: 'bg-[var(--coverage-pie-fi)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieDotOpt: 'bg-[var(--coverage-pie-opt)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieDotStock: 'bg-[var(--coverage-pie-stock)] shadow-[0 0 0 1px rgba(0, 0, 0, 0.35)]',
  coverageAssetPieHeader: 'flex items-center flex-wrap [gap:0.35rem 0.5rem] [margin-bottom:0.45rem]',
  coverageAssetPieLegend: 'flex flex-col [gap:0.28rem] min-w-0',
  coverageAssetPieLegendDivider: '[height:1px] bg-[var(--color-border, #2a313c)] [margin:0.1rem 0]',
  coverageAssetPieLegendItem: 'grid [grid-template-columns:10px 1fr auto auto] items-center [gap:0.4rem 0.55rem] [font-size:0.8rem]',
  coverageAssetPieLegendLabel: 'text-[var(--color-text-muted, #7a8492)] whitespace-nowrap',
  coverageAssetPieLegendMixCol: 'flex flex-col [gap:0.28rem] min-w-0',
  coverageAssetPieLegendPct: 'tabular-nums font-semibold text-[var(--color-text-muted, #7a8492)] [font-size:0.76rem] [min-width:2.75rem] text-right',
  coverageAssetPieLegendValue: 'tabular-nums font-semibold text-[var(--color-text-main, #e4e9ef)] whitespace-nowrap text-right',
  coverageAssetPieRingSegBp: '[stroke:var(--coverage-pie-bp)]',
  coverageAssetPieRingSegCash: '[stroke:var(--coverage-pie-cash)]',
  coverageAssetPieRingSegCashlike: '[stroke:var(--coverage-pie-cashlike)]',
  coverageAssetPieRingSegFi: '[stroke:var(--coverage-pie-fi)]',
  coverageAssetPieRingSegOpt: '[stroke:var(--coverage-pie-opt)]',
  coverageAssetPieRingSegStock: '[stroke:var(--coverage-pie-stock)]',
  coverageAssetPieSvg: 'shrink-0 [filter:drop-shadow(0 2px 10px rgba(0, 0, 0, 0.4))]',
  coverageAssetPieTitle: '[font-size:0.78rem] font-semibold text-[var(--color-text-muted, #7a8492)] uppercase [letter-spacing:0.04em]',
  coverageAvailableContracts: '[font-size:1.15rem] [font-weight:800] tabular-nums text-[var(--color-accent-bright, #7dd3fc)] [line-height:1.15] [letter-spacing:0.02em]',
  coverageAvailableContractsLabel: '[font-size:0.68rem] font-semibold uppercase [letter-spacing:0.06em] text-[var(--color-text-muted, #7a8492)] [margin-top:0.1rem]',
  coverageAvailableHeldAmtCell: 'text-center align-middle [min-width:4.5rem]',
  coverageAvailableHeldAmtSlim: 'text-center',
  coverageAvailableSharesLine: '[margin-top:0.35rem] [font-size:0.82rem] font-bold tabular-nums text-[var(--color-text-main, #e4e9ef)]',
  coverageChartsCell: 'min-w-0',
  coverageChartsGrid: 'grid [grid-template-columns:repeat(auto-fit, minmax(min(100%, 18rem), 1fr))] [gap:1rem 1.25rem] [align-items:start]',
  coverageChartsSection: 'mb-[var(--space-4, 1rem)] [padding:0.55rem 0.65rem 0.65rem] rounded-[var(--radius-md, 6px)] [border:1px solid var(--color-border, #2a313c)] bg-[linear-gradient( 165deg, rgba(255, 255, 255, 0.03) 0%, var(--color-surface-elevated, #1a1f26) 100% )] shadow-[inset 0 1px 0 rgba(255, 255, 255, 0.04)]',
  coverageChartsToolbar: 'flex flex-wrap items-center justify-between [gap:0.45rem 0.75rem] [margin-bottom:0.65rem] [padding-bottom:0.5rem] [border-bottom:1px solid var(--color-border, #2a313c)]',
  coverageChartsToolbarLabel: '[font-size:0.72rem] font-bold uppercase [letter-spacing:0.05em] text-[var(--color-text-muted, #7a8492)]',
  coverageCostAvgBasis: 'font-semibold',
  coverageCostAvgCell: 'text-right tabular-nums align-middle [line-height:1.25] [min-width:4.5rem]',
  coverageCostAvgPerShare: '[font-size:0.82em] font-medium text-[var(--color-text-muted, #7a8492)] [margin-top:0.06rem]',
  coverageHeldSharesCell: 'tabular-nums',
  coverageMktValuePerShare: '[font-size:0.82em] font-medium text-[var(--color-text-muted, #7a8492)] [margin-top:0.06rem]',
  coverageMktValuePriceCell: 'text-right tabular-nums align-middle [line-height:1.25] [min-width:5rem]',
  coverageMktValueTotal: 'font-semibold',
  coveragePnlStackedCell: 'tabular-nums text-right align-middle [line-height:1.25] [min-width:4rem]',
  coveragePnlStackedTh: 'whitespace-nowrap',
  coveragePoolPanel: 'min-w-0 overflow-x-auto [padding:0.35rem 0.5rem 0.5rem] rounded-[var(--radius-md, 6px)] [border:1px solid var(--color-border, #2a2f38)] bg-[var(--color-surface-raised, rgba(0, 0, 0, 0.12))]',
  coveragePoolThBackedAmt: '[display:inline-block] [line-height:1.15] text-center [font-size:0.78rem] font-semibold whitespace-normal align-middle',
  coveragePoolThHeldAmt: '[display:inline-block] [line-height:1.15] text-center [font-size:0.78rem] font-semibold whitespace-normal align-middle',
  coverageSectionAccountFilter: 'flex flex-wrap [gap:0.2rem]',
  coverageSharedHint: '[font-size:0.82em] text-[var(--color-text-muted, #7a8492)] [margin-left:0.25em]',
  coverageStatusBadge: 'inline-block whitespace-nowrap rounded px-[0.55em] py-[0.1em] text-[0.82em] font-semibold tracking-[0.02em]',
  coverageStatusCovered: 'bg-[rgba(74, 222, 128, 0.14)] text-[#4ade80]',
  coverageStatusNaked: 'bg-[rgba(248, 113, 113, 0.14)] text-[#f87171]',
  coverageStatusPartial: 'bg-[rgba(251, 191, 36, 0.14)] text-[#fbbf24]',
  coverageSummaryIntro: '[margin-bottom:0.55rem]',
  coverageSummaryPlaceholderText: '[margin:0.35rem 0 0] [max-width:52rem] [line-height:1.45]',
  coverageSummarySection: 'mb-[var(--space-4, 1rem)] p-[var(--space-2) 0]',
  coverageSummaryTable: '[max-width:48rem]',
  daemonCardTitle: '[margin:0 0 0.25rem 0] [font-size:1.25rem] font-semibold [line-height:1.3]',
  daemonGroup: '[flex:1] [min-width:200px] [border:1px solid var(--color-border)] [border-radius:10px] p-[var(--space-3) var(--space-4)] bg-[var(--color-surface-elevated)] shadow-[0 1px 2px rgba(0, 0, 0, 0.15)]',
  daemonGroupBody: 'text-[length:var(--text-body)]',
  daemonGroupHeader: 'flex items-center gap-[var(--space-2)] mb-[var(--space-2)]',
  daemonGroups: 'flex flex-row flex-wrap gap-[var(--space-3)] [margin-top:0]',
  daemonGroupTitle: 'text-[length:var(--text-tiny)] font-semibold uppercase [letter-spacing:0.06em] text-[var(--color-text-muted)] m-0',
  daemonHeaderMain: '[flex:1] min-w-0',
  dashboardOpenOrdersBtn: 'inline-flex items-center gap-[var(--space-2)] [padding:0.35rem 0.55rem] [border:1px solid var(--color-border)] [border-radius:999px] bg-[var(--color-surface-elevated)] [color:inherit] text-[length:var(--text-caption)] font-semibold cursor-pointer',
  dashboardOpenOrdersCluster: 'inline-flex items-center min-w-0',
  dashboardOpenOrdersLabel: 'text-[var(--color-text-muted)]',
  dashboardOpenOrdersValue: 'tabular-nums text-[var(--color-text-main)] [min-width:1.25rem] text-right',
  dashboardStreamsBtn: 'cursor-pointer font-[inherit] [color:inherit] text-left',
  dashboardStreamsCluster: '[flex:1 1 24rem]',
  dashboardStreamsInline: 'min-w-0 [flex:1 1 auto] inline-flex items-center gap-[var(--space-2)] [padding:0.35rem 0.55rem] [border:1px solid var(--color-border)] [border-radius:999px] bg-[var(--color-surface-elevated)] overflow-hidden',
  dashboardStreamsItem: 'relative inline-flex items-center gap-[var(--space-2)] whitespace-nowrap text-[length:var(--text-caption)] font-semibold text-[var(--color-text-main)]',
  dashboardStreamsItemLabel: 'text-[var(--color-text-muted)]',
  dashboardStreamsMarquee: 'min-w-0 [flex:1 1 auto] overflow-hidden [mask-image:linear-gradient(90deg, transparent 0, #000 3%, #000 97%, transparent 100%)] [-webkit-mask-image:linear-gradient(90deg, transparent 0, #000 3%, #000 97%, transparent 100%)]',
  dashboardStreamsTrack: 'inline-flex items-center gap-[var(--space-4)] [min-width:max-content]',
  dashboardStrip: 'p-[var(--space-2) var(--space-3)]',
  dashboardStripGrid: 'flex flex-wrap items-center gap-[var(--space-3)]',
  dataBarsChart: 'w-full min-w-0',
  dataBarsChartBrushHint: '[margin:0 0 0.5rem] text-[length:var(--text-caption, 0.8125rem)] text-[var(--color-text-muted)] [line-height:1.4]',
  dataBarsChartHeader: 'flex flex-wrap items-baseline justify-between gap-[var(--space-2)] mb-[var(--space-2)]',
  dataBarsChartLegend: 'mt-[var(--space-2)] flex flex-wrap gap-[var(--space-3)] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  dataBarsChartLegendTime: 'font-medium text-[var(--color-text)]',
  dataBarsChartRangeBar: 'flex flex-wrap items-center [gap:0.5rem 0.75rem] [margin-top:0.5rem] text-[length:var(--text-caption, 0.8125rem)] text-[var(--color-text-muted)]',
  dataBarsChartRangeReset: '[padding:0.2rem 0.55rem] [font-size:inherit] [border-radius:999px] [border:1px solid var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text)] cursor-pointer',
  dataBarsChartSvg: 'w-full min-w-0 [height:320px] block',
  dataBarsChartTitle: 'font-semibold text-[length:var(--text-body-strong, 0.98rem)]',
  dataCoverageActionsNowrap: 'whitespace-nowrap flex items-center [gap:0.35rem]',
  dataCoverageActionsSub: 'text-[length:var(--font-size-sm)] font-semibold text-[var(--color-text-muted)] text-center',
  dataCoverageActionsSyncSplit: 'text-center [vertical-align:bottom] whitespace-nowrap',
  dataCoverageBarsBtn: 'bg-none border-0 p-0 font-[inherit] [color:inherit] cursor-pointer text-left',
  dataCoverageEndWarning: 'text-[var(--color-warning, #d97706) !important] font-semibold',
  dataCoverageRangeLine: 'tabular-nums whitespace-nowrap',
  dataCoverageRangeStack: 'flex flex-col items-start [gap:0.12rem]',
  dataCoverageRefPolygon: '[margin-left:0.15rem] text-[var(--color-text-muted)] [font-weight:normal] [font-size:0.9em] whitespace-nowrap',
  dataCoverageSyncPairRow: 'inline-flex flex-nowrap items-center justify-center [gap:0.5rem] [min-width:max-content]',
  dataPullRangeCustom: 'mb-[var(--space-4)] p-[var(--space-3)] bg-[var(--color-surface-elevated)] [border-radius:8px] [border:1px solid var(--color-border)]',
  dataPullRangeCustomRow: 'flex items-center gap-[var(--space-2)] mb-[var(--space-2)] text-[length:var(--text-body)]',
  dataPullRangeDesc: 'm-[0 0 var(--space-3)] text-[var(--color-text-muted)] text-[length:var(--text-body)]',
  dataPullRangeModal: 'max-w-[420px]',
  dataPullRangeOption: 'flex items-start gap-[var(--space-2)] cursor-pointer text-[length:var(--text-body)]',
  dataPullRangeOptions: 'flex flex-col gap-[var(--space-2)] mb-[var(--space-4)]',
  dataPullRangePeriodCheck: 'inline-flex items-center gap-[var(--space-2)] cursor-pointer text-[length:var(--text-body)]',
  dataPullRangePeriods: 'flex flex-wrap items-center gap-[var(--space-2) var(--space-3)] mb-[var(--space-4)]',
  dataPullRangePeriodsLabel: 'w-full text-[length:var(--text-body)] font-medium',
  dataResetModalActions: 'flex gap-[var(--space-3)] justify-end',
  dataResetPeriodCheck: 'inline-flex items-center gap-[var(--space-2)] cursor-pointer text-[length:var(--text-body)]',
  dataResetPeriods: 'flex flex-wrap gap-[var(--space-3)] mb-[var(--space-4)]',
  detailExecIndentStack: 'flex flex-col items-start [gap:0.15rem] min-w-0',
  detailExecLinePrimary: '[line-height:1.25]',
  detailExecLineSync: '[padding-left:0.1rem] [margin-top:0.1rem]',
  detailExecSyncBtn: 'text-[var(--color-accent, #6ab0ff)] [opacity:0.95]',
  detailExecutionRow: 'bg-[var(--color-surface-elevated)] [font-size:0.88em]',
  draggableExplainPanelBody: 'p-[var(--space-4) var(--space-5)] [overflow-y:auto] [flex:1 1 auto] [min-height:0] text-[length:var(--text-body)] text-[var(--color-text-muted)] [line-height:1.55]',
  draggableExplainPanelClose: 'shrink-0 [width:2rem] [height:2rem] inline-flex items-center justify-center border-0 [border-radius:6px] [background:transparent] text-[var(--color-text-muted)] [font-size:1.35rem] [line-height:1] cursor-pointer',
  draggableExplainPanelHeader: 'flex items-start justify-between gap-[var(--space-3)] p-[var(--space-3) var(--space-4)] [border-bottom:1px solid var(--color-border)] [cursor:grab] select-none shrink-0',
  draggableExplainPanelHint: 'm-0 p-[var(--space-3) var(--space-5)] [border-top:1px solid var(--color-border)] text-[length:var(--text-caption)] text-[var(--color-text-dim)] shrink-0 [line-height:1.45]',
  draggableExplainPanelTitle: 'm-0 text-[length:var(--text-title)] font-bold text-[var(--color-text-main)] [line-height:1.35] [padding-right:var(--space-2)]',
  gatesFormActions: 'flex gap-[var(--space-2)] mt-[var(--space-2)]',
  gatesFormGroup: 'flex flex-col gap-[var(--space-2)]',
  gatesFormGroupTitle: 'text-[length:var(--text-body)] font-semibold text-[var(--color-text-main)] m-[0 0 var(--space-1) 0]',
  gatesFormRow: 'flex items-center gap-[var(--space-2)] flex-wrap',
  ibAccountsContent: 'bg-[var(--color-surface-elevated)] [border:1px solid var(--color-border)] [border-radius:8px] p-[var(--space-4)] min-w-0',
  ibAccountsOptDetails: '[text-align:left !important] [white-space:normal !important] tabular-nums',
  ibAccountsOptDetailsInstance: '[font-size:0.72rem] overflow-hidden [text-overflow:ellipsis]',
  ibAccountsOptDetailsK: 'text-[var(--color-text-muted)] font-semibold [font-size:0.68rem] uppercase [letter-spacing:0.04em]',
  ibAccountsOptDetailsLines: 'flex flex-col [gap:2px] [max-width:15rem]',
  ibAccountsOptDetailsStrategy: 'text-[length:var(--text-caption)] overflow-hidden [text-overflow:ellipsis]',
  ibAccountsTabCount: 'ml-[var(--space-1)] [font-weight:400] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  ibPositionsEmpty: 'text-[length:var(--text-body)] text-[var(--color-text-muted)] m-[var(--space-1) 0 0 0] p-[var(--space-2) 0]',
  ibPositionsStockTotalsK: '[flex:none]',
  ibPositionsStockTotalsMetric: 'inline-flex items-baseline [gap:0.35rem] [flex:0 0 auto] whitespace-nowrap',
  ibPositionsStockTotalsV: '[display:inline-block] [min-width:11rem] text-right tabular-nums',
  ibPositionsStockTotalsVWide: '[min-width:15rem]',
  ibPositionsTable: 'w-full border-collapse text-[length:var(--text-caption)]',
  ibPositionsTitle: 'text-[length:var(--text-tiny)] font-semibold uppercase [letter-spacing:0.05em] text-[var(--color-text-muted)] m-[var(--space-3) 0 var(--space-2) 0]',
  ibStockGroupHeaderBtn: 'bg-none border-0 [color:inherit] font-[inherit] [font-weight:inherit] p-0 m-0 cursor-pointer text-left no-underline rounded-[var(--radius-sm, 4px)]',
  ibSummaryIbSection: '[grid-column:span 2] [min-width:200px] flex flex-wrap gap-[var(--space-3)] items-start',
  ibSummaryItem: 'flex flex-col gap-[var(--space-1)]',
  ibSummaryPanel: 'bg-[var(--color-surface-elevated)] [border:1px solid var(--color-border)] [border-radius:12px] p-[var(--space-4)] mb-[var(--space-4)] [box-shadow:0 1px 3px var(--color-dashboard-shadow)]',
  ibSummaryRow: 'grid [grid-template-columns:repeat(auto-fill, minmax(140px, 1fr))] gap-[var(--space-3)] text-[length:var(--text-body)]',
  infoTooltipIcon: 'inline-flex items-center justify-center [width:1.1rem] [height:1.1rem] [font-size:0.75rem] font-semibold [line-height:1] text-[var(--color-text-muted)] [border:1px solid var(--color-border)] [border-radius:50%] bg-[var(--color-surface-elevated)]',
  infoTooltipPopup: 'absolute [left:50%] [transform:translateX(-50%)] [top:calc(100% + 0.5rem)] [z-index:100] [max-width:20rem] [padding:0.5rem 0.75rem] text-[length:var(--text-caption)] [font-weight:normal] [line-height:1.4] text-[var(--color-text-muted)] [/* Match replay filter inputs (e.g. Search symbol) — low-contrast, not a loud card */ background:var(--color-bg)] [border:1px solid var(--color-border)] [border-radius:6px] shadow-[0 1px 4px rgba(0, 0, 0, 0.12)] whitespace-normal [opacity:0] [pointer-events:none]',
  infoTooltipWrap: 'inline-flex items-center justify-center [cursor:help] align-middle relative',
  instanceListSymbolToolbarHint: '[flex:1 1 100%] m-0 [font-size:0.72rem] [line-height:1.35]',
  instanceSheetBadge: '[display:inline-block] [padding:0.1rem 0.45rem] [border-radius:4px] [font-size:0.8em] font-medium [letter-spacing:0.01em] [/* default fallback */ background:rgba(148, 163, 184, 0.12)] text-[#94a3b8]',
  instanceSheetDetailCell: 'p-[var(--space-2) var(--space-3) var(--space-3) !important] [border-top:none !important] [/* Colspan row:without this, nested wide tables expand the parent and the outer wrap gets a horizontal scrollbar. */ max-width: 0] overflow-x-auto [overflow-y:visible] [-webkit-overflow-scrolling:touch]',
  instanceSheetDetailRow: 'bg-[var(--color-surface, #13171d)]',
  instanceSheetExecQtyCell: '[max-width:14rem] whitespace-normal [line-height:1.3] tabular-nums',
  instanceSheetFilterBubbleLabel: '[font-size:0.72rem] font-semibold text-[var(--color-text-muted, #8b949e)] uppercase [letter-spacing:0.05em] shrink-0',
  instanceSheetFilterBubbleRow: 'inline-flex flex-wrap items-center [gap:0.5rem 0.75rem]',
  instanceSheetInstLink: 'text-[var(--color-link, #7dd3fc)] font-semibold no-underline',
  instanceSheetInstSublabel: '[font-size:0.8em] block overflow-hidden [text-overflow:ellipsis]',
  instanceSheetOppCell: 'flex flex-col [gap:0.1rem] min-w-0',
  instanceSheetOppName: 'text-[var(--color-text-main, #e4e9ef)] font-medium [line-height:1.35]',
  instanceSheetRowExpanded: 'bg-[var(--color-surface-elevated, #1a1f26)] [border-bottom:none]',
  instanceSheetStockSection: 'mt-[var(--space-4, 1rem)] [padding-top:var(--space-3, 0.75rem)] [border-top:1px solid var(--color-border, #2a2f38)]',
  instanceSheetSubSection: 'mb-[var(--space-3)]',
  instanceSheetSubTable: '[font-size:0.92em]',
  instanceSheetSymbols: '[font-family:var(--font-mono, \'JetBrains Mono\', monospace)] [font-size:0.82em] text-[var(--color-text-main, #e4e9ef)] [letter-spacing:0.02em]',
  instanceSheetSymbolsButtons: 'flex flex-wrap items-center [gap:0.15rem 0.35rem]',
  instanceSheetSymbolsSep: 'text-[var(--color-text-muted)] select-none',
  instanceSheetTable: 'w-full [table-layout:fixed]',
  ledgerAccountBubbleActive: 'border-[var(--color-primary, #2563eb)] bg-[linear-gradient(165deg, rgba(37, 99, 235, 0.28) 0%, rgba(37, 99, 235, 0.12) 100%)] text-[var(--color-text-main, #e4e9ef)] shadow-[0 0 0 1px rgba(37, 99, 235, 0.4), 0 2px 8px rgba(0, 0, 0, 0.2)]',
  ledgerExpiryComboboxInput: 'w-full [cursor:text] [text-overflow:ellipsis]',
  ledgerFilterAccountBubbles: 'inline-flex flex-wrap items-center [gap:0.2rem]',
  ledgerFilterComboboxEmpty: '[padding:0.5rem 0.65rem] text-[length:var(--text-small, 0.875rem)] text-[var(--color-text-muted, #8b95a3)] [cursor:default]',
  ledgerFilterComboboxList: 'absolute [left:0] [right:0] [top:calc(100% + 3px)] [z-index:90] m-0 p-[var(--space-1, 4px) 0] list-none [max-height:min(280px, 45vh)] overflow-auto bg-[var(--color-surface, #13171d)] [border:1px solid var(--color-border, #2a313c)] rounded-[var(--radius-sm, 6px)] shadow-[0 8px 24px rgba(0, 0, 0, 0.35)]',
  ledgerFilterComboboxValueDim: 'text-[var(--color-text-dim)]',
  ledgerFilterComboboxOptionSub: '[font-size:0.78em] text-[var(--color-text-muted, #8b95a3)] [word-break:break-word]',
  ledgerFilterComboboxOptionSymbol: 'flex-row items-center',
  ledgerFilterComboboxOptionTitle: 'font-medium',
  ledgerInstanceControlsRow: 'flex flex-wrap items-center gap-[var(--space-2) var(--space-4)] w-full min-w-0',
  ledgerInstanceFilterMetaRow: 'flex items-center flex-wrap [gap:0.75rem] [margin-top:0.25rem] [font-size:0.75rem] text-[var(--color-text-muted, #8b949e)]',
  ledgerInstanceToolbarRow: 'items-start [row-gap:var(--space-2)]',
  ledgerInstanceToolbarSegment: 'inline-flex flex-wrap items-center [gap:0.35rem 0.55rem] min-w-0',
  ledgerInstanceToolbarSep: '[width:1px] [align-self:stretch] [min-height:1.65rem] bg-[var(--color-border-subtle, rgba(255, 255, 255, 0.08))] shrink-0',
  ledgerMetricExplainFormula: 'm-[var(--space-3) 0] p-[var(--space-3) var(--space-4)] [border-radius:10px] [border:1px solid var(--color-border)] bg-[var(--color-bg)] [font-family:var(--font-mono)] text-[length:var(--text-caption)] [line-height:1.5] text-[var(--color-text-main)] [white-space:pre-wrap] overflow-x-auto',
  ledgerMetricExplainFormulaCompact: 'm-[var(--space-1) 0]',
  ledgerMetricExplainLiveMetric: 'text-[var(--color-text-main)]',
  ledgerMetricExplainLiveRaw: 'font-medium text-[var(--color-text-dim)] [font-family:var(--font-mono)] text-[length:var(--text-caption)]',
  ledgerMetricExplainLiveSub: 'm-[var(--space-3) 0 var(--space-2)] text-[length:var(--text-body)] font-semibold text-[var(--color-text-main)]',
  ledgerMetricExplainNote: 'm-[var(--space-4) 0 0] text-[length:var(--text-caption)] text-[var(--color-text-dim)] [line-height:1.55]',
  ledgerMetricExplainSection: 'm-[var(--space-4) 0 var(--space-3)] text-[length:var(--text-body)] font-bold text-[var(--color-accent)] [letter-spacing:0.02em]',
  ledgerMetricExplainTable: 'w-full border-collapse text-[length:var(--text-caption)] [font-family:var(--font-mono)]',
  ledgerMetricExplainTableWrap: 'mt-[var(--space-3)] [max-height:min(52vh, 30rem)] overflow-auto [border-radius:10px] [border:1px solid var(--color-border)]',
  ledgerOptInstanceFilterCount: '[font-size:0.75rem] text-[var(--color-text-muted, #8b949e)] [margin-left:0.2rem] [opacity:0.8]',
  ledgerOptInstanceFilterLabel: '[font-size:0.78rem] font-semibold text-[var(--color-text-muted, #8b949e)] whitespace-nowrap',
  ledgerOptionsSubtabRowInSheet: '[margin-bottom:0]',
  ledgerOptLinkStockBadges: 'inline-flex flex-wrap [gap:0.25rem] [margin-left:0.35rem] align-middle',
  ledgerPaginationBtn: '[appearance:none] [border:1px solid var(--color-border, var(--border-subtle, #2a313c))] [background:transparent] text-[var(--color-text-muted, #8b949e)] [font-size:0.85rem] font-semibold [line-height:1] [width:1.85rem] [height:1.85rem] [border-radius:4px] cursor-pointer [font-family:inherit] inline-flex items-center justify-center',
  ledgerPaginationInfo: 'text-[var(--color-text-muted, #8b949e)] [font-size:0.8rem] [padding:0 0.25rem] [min-width:3.5rem] text-center',
  ledgerPaginationTotal: 'text-[var(--color-text-muted, #8b949e)] [font-size:0.75rem] [opacity:0.7]',
  ledgerStkCellCategory: '[display:inline-block] [padding:0.08rem 0.4rem] [border-radius:4px] font-medium bg-[color-mix(in srgb, #a855f7 12%, transparent)] [border:1px solid color-mix(in srgb, #a855f7 26%, transparent)]',
  ledgerStkCellSymbol: '[display:inline-block] [padding:0.08rem 0.4rem] [border-radius:4px] font-semibold bg-[color-mix(in srgb, var(--color-accent, #3b82f6) 14%, transparent)] [border:1px solid color-mix(in srgb, var(--color-accent, #3b82f6) 28%, transparent)]',
  ledgerStkUrPnlGroupInlineMetrics: 'inline-flex items-baseline [gap:0.3rem] flex-nowrap [font-size:0.92em]',
  ledgerStkUrPnlGroupMetricSep: 'text-[var(--color-text-muted)] select-none',
  ledgerStkUrPnlPrefix: 'font-semibold [opacity:0.88] [margin-right:0.12rem]',
  ledgerStkUrPnlUnrealized: 'text-[var(--color-warning)]',
  ledgerStockBucketFilterRow: 'flex flex-wrap items-center gap-[var(--space-2) var(--space-3)] w-full min-w-0',
  ledgerStockBucketFilterSep: '[width:1px] [align-self:stretch] [min-height:1.65rem] bg-[var(--color-border-subtle, rgba(255, 255, 255, 0.08))] shrink-0',
  ledgerStockQuickJournalBtn: '[margin-left:auto] shrink-0',
  ledgerStrategyFilterBubbles: 'flex flex-wrap [gap:0.3rem]',
  ledgerStrategyFilterClear: '[appearance:none] border-0 [background:transparent] text-[var(--color-accent, #58a6ff)] [font-size:0.75rem] [font-family:inherit] cursor-pointer p-0 underline [text-underline-offset:2px]',
  ledgerStrategyFilterLabel: '[font-size:0.75rem] font-semibold text-[var(--color-text-muted, #8b949e)] whitespace-nowrap [min-width:4.5rem]',
  ledgerStrategyFilterMeta: 'flex items-center [gap:0.75rem] [margin-top:0.15rem] [font-size:0.75rem] text-[var(--color-text-muted, #8b949e)]',
  ledgerStrategyFilterRow: 'flex items-center flex-wrap [gap:0.35rem 0.6rem]',
  ledgerSymbolComboboxInput: 'w-full [cursor:text]',
  ledgerTabFiltersSection: 'flex flex-col gap-[var(--space-2)]',
  ledgerTradePeriodLabel: 'text-[length:var(--text-caption)] text-[var(--color-text-muted)] whitespace-nowrap',
  liveStrategyInlineBar: 'flex items-center gap-[var(--space-2)] [padding:0.4rem 0.6rem] bg-[color-mix(in srgb, var(--color-border) 25%, var(--color-surface-elevated))] [border:1px solid var(--color-border)] rounded-[var(--radius-md)] flex-wrap [row-gap:var(--space-1)]',
  liveStrategyInlinePills: 'flex items-center gap-[var(--space-2)] flex-wrap',
  liveStrategyInlineTitle: '[font-size:0.68rem] font-bold uppercase [letter-spacing:0.07em] text-[var(--color-text-muted)] inline-flex items-center [gap:0.25rem] [margin-right:var(--space-1)] shrink-0',
  liveStrategyPill: 'inline-flex items-baseline [gap:0.25rem] [font-size:0.75rem]',
  liveStrategyPillKey: '[font-size:0.62rem] font-bold text-[var(--color-text-muted)] bg-[var(--color-border)] [padding:0.05rem 0.3rem] [border-radius:3px] uppercase [letter-spacing:0.04em]',
  liveStrategyPillVal: 'font-semibold text-[var(--color-text)] [font-size:0.75rem]',
  massiveDelayOhlcQueueLabel: '[margin-bottom:0]',
  massiveDelayOhlcQueueSwitchWrap: 'inline-flex flex-wrap items-center gap-[var(--space-2)] shrink-0 [margin-left:auto]',
  massiveDelayOhlcQueueTopline: 'flex flex-wrap items-start justify-between gap-[var(--space-3)] mb-[var(--space-3)]',
  massiveDelayRefHeadingActions: 'flex flex-wrap items-center gap-[var(--space-2)] shrink-0',
  monitorHeaderActions: '[margin-left:auto] inline-flex items-center gap-[var(--space-2)]',
  msgError: 'text-[var(--color-danger)]',
  msgOk: 'text-[var(--color-lamp-green)]',
  msgWarning: 'text-[var(--color-warning)]',
  openOrdersFreshnessAge: 'font-bold [text-shadow:0 0 5px var(--color-accent-glow, var(--color-accent))]',
  oppColBody: 'p-[var(--space-3)] flex flex-col gap-[var(--space-3)]',
  oppColHeader: 'p-[var(--space-2) var(--space-3)] bg-[var(--color-surface-elevated)] [border-bottom:1px solid var(--color-border)]',
  oppColTitle: 'text-[length:var(--text-caption)] font-bold m-0 uppercase [letter-spacing:0.05em] text-[var(--color-text-muted)]',
  oppConditionInput: '[flex:1] min-w-0 p-[var(--space-1) var(--space-2)] bg-[var(--color-surface)] [border:1px solid var(--color-border)] [border-radius:4px] text-[var(--color-text-main)] text-[length:var(--text-caption)]',
  oppConditionInputNum: '[flex:0 0 5rem] [font-family:var(--font-mono)] tabular-nums',
  oppConditionRemove: 'flex items-center justify-center [width:22px] [height:22px] border-0 [background:transparent] text-[var(--color-text-dim)] [font-size:0.9rem] [border-radius:4px] cursor-pointer shrink-0',
  oppConditionRow: 'flex items-center gap-[var(--space-2)] p-[var(--space-2)] bg-[var(--color-bg)] [border:1px solid var(--color-border)] [border-radius:6px]',
  oppConditionSelect: '[flex:0 0 auto] [min-width:7rem] p-[var(--space-1) var(--space-2)] bg-[var(--color-surface)] [border:1px solid var(--color-border)] [border-radius:4px] text-[var(--color-text-main)] text-[length:var(--text-caption)] cursor-pointer',
  oppCreateBtn: '[letter-spacing:0.01em]',
  oppFieldHint: 'text-[length:var(--text-caption)] text-[var(--color-text-dim)] m-0',
  oppFieldLabel: 'text-[length:var(--text-caption)] font-semibold text-[var(--color-text-muted)] uppercase [letter-spacing:0.05em]',
  oppFieldName: '[flex:1] [min-width:16rem]',
  oppFieldToggle: '[padding-bottom:var(--space-1)] shrink-0',
  oppFormBody: 'p-[var(--space-4) var(--space-5)] flex flex-col gap-[var(--space-4)]',
  oppFormClose: '[width:28px] [height:28px] flex items-center justify-center border-0 [background:transparent] text-[var(--color-text-muted)] [font-size:1.25rem] [line-height:1] [border-radius:6px] cursor-pointer',
  oppFormError: 'flex items-center gap-[var(--space-2)] m-[var(--space-3) var(--space-5) 0] p-[var(--space-2) var(--space-3)] bg-[var(--color-danger-soft)] [border:1px solid var(--color-danger)] [border-radius:6px] text-[var(--color-danger)] text-[length:var(--text-caption)] font-medium',
  oppFormErrorIcon: 'inline-flex items-center justify-center [width:18px] [height:18px] [border-radius:50%] bg-[var(--color-danger)] text-[#fff] [font-size:0.7rem] font-bold shrink-0',
  oppFormHeader: 'flex justify-between items-center p-[var(--space-3) var(--space-5)] bg-[var(--color-surface-elevated)] [border-bottom:1px solid var(--color-border)]',
  oppFormLoading: 'p-[var(--space-4) var(--space-5)] text-[var(--color-text-muted)] text-[length:var(--text-caption)]',
  oppFormTitle: 'text-[length:var(--text-title)] font-bold m-0 [letter-spacing:-0.01em]',
  oppGatePillSelected: 'bg-[var(--color-accent-soft)] border-[var(--color-accent)] text-[var(--color-accent)] font-semibold',
  oppGatePillVersion: 'text-[length:var(--text-tiny)] [opacity:0.7]',
  oppInput: 'p-[var(--space-2) var(--space-3)] bg-[var(--color-bg)] [border:1px solid var(--color-border)] [border-radius:6px] text-[var(--color-text-main)] text-[length:var(--text-body)] [font-family:var(--font-sans)]',
  oppListActions: 'flex items-center gap-[var(--space-3)] flex-wrap',
  oppListTitle: 'text-[length:var(--text-title)] font-bold m-0 [letter-spacing:-0.01em]',
  oppListToolbar: 'flex justify-between items-center flex-wrap gap-[var(--space-3)] mb-[var(--space-3)]',
  oppRowAction: 'p-[var(--space-1) var(--space-3)] [border-radius:5px] text-[length:var(--text-caption)] font-medium cursor-pointer [border:1px solid transparent]',
  oppRowActionCopy: '[background:transparent] text-[var(--color-text-muted)] border-[var(--color-border)]',
  oppRowActionEdit: 'bg-[var(--color-accent-soft)] text-[var(--color-accent)] [border-color:transparent]',
  oppStructurePanelMeta: '[font-size:0.75rem] text-[var(--color-text-muted)] [line-height:1.3]',
  oppStructurePanels: 'grid [grid-template-columns:repeat(auto-fill, minmax(11rem, 1fr))] gap-[var(--space-2)] [max-height:16rem] [overflow-y:auto] [flex:1] min-w-0',
  oppStructurePanelSelected: 'bg-[var(--color-accent-soft)] border-[var(--color-accent)] text-[var(--color-accent)] [box-shadow:0 0 0 2px var(--color-accent)]',
  oppStructurePanelTitle: 'font-semibold [line-height:1.3] [margin-bottom:0.15rem]',
  oppSymbolTag: 'inline-flex items-center bg-[var(--color-bg)] [border:1px solid var(--color-border)] [border-radius:5px] overflow-hidden',
  oppSymbolTagInput: '[width:5.5rem] p-[var(--space-1) var(--space-2)] border-0 [background:transparent] text-[var(--color-text-main)] text-[length:var(--text-caption)] [font-family:var(--font-mono)] font-semibold [letter-spacing:0.03em]',
  oppSymbolTagRemove: 'flex items-center justify-center [width:22px] [height:100%] border-0 [border-left:1px solid var(--color-border)] [background:transparent] text-[var(--color-text-dim)] [font-size:0.85rem] cursor-pointer p-[var(--space-1) 0]',
  oppSymbolTags: 'flex flex-wrap gap-[var(--space-2)]',
  oppTable: 'm-0',
  oppTableNameCell: 'font-semibold',
  oppTableNone: 'text-[var(--color-text-dim)]',
  oppTableRowActions: 'inline-flex gap-[var(--space-1)]',
  oppTableScopeText: 'block overflow-hidden [text-overflow:ellipsis] whitespace-nowrap',
  oppTableWrap: 'overflow-x-auto [border:1px solid var(--color-border)] [border-radius:8px]',
  oppWatchlistStkActions: 'flex flex-wrap items-center gap-[var(--space-2)] mb-[var(--space-2)]',
  oppWatchlistStkCheck: 'inline-flex items-center gap-[var(--space-2)] cursor-pointer text-[length:var(--text-caption)] text-[var(--color-text-main)] p-[var(--space-1) var(--space-2)] m-[0 calc(-1 * var(--space-2)) 0 0] [border-radius:6px]',
  oppWatchlistStkList: '[flex:1] min-w-0',
  oppWatchlistStkSymbols: 'list-none m-0 p-[var(--space-2) var(--space-3)] bg-[var(--color-surface-elevated)] [border:1px solid var(--color-border)] [border-radius:8px] [max-height:14rem] [overflow-y:auto] overflow-x-hidden [column-count:3] [column-gap:var(--space-4)] [column-fill:balance]',
  optionUnderlyingPoolCashBp: 'tabular-nums [font-size:0.92em] font-semibold text-[var(--color-text-secondary, #c4cad4)]',
  optionUnderlyingPoolTotalLabel: 'text-[var(--color-text-muted, #7a8492)] font-medium',
  optionUnderlyingPoolTotals: '[font-size:0.88rem] text-[var(--color-text-secondary, #c4cad4)]',
  optionUnderlyingPoolTotalSep: 'text-[var(--color-text-muted, #5c6570)]',
  performanceByDayNotional: 'text-[var(--color-text-dim)] tabular-nums',
  performanceCalendarAssetTabs: 'flex flex-wrap gap-[var(--space-2)] mb-[var(--space-3)]',
  performanceCalendarCell: 'flex flex-col items-center justify-center [min-height:0] [height:100%] p-[var(--space-1)] bg-[var(--color-surface-elevated)] [border:1px solid var(--color-border)] [border-radius:6px] text-[length:var(--text-caption)] overflow-hidden',
  performanceCalendarContractGroup: 'mt-[var(--space-4)] [padding-top:var(--space-3)] [border-top:1px solid var(--color-border)]',
  performanceCalendarContractTitle: 'm-[0 0 var(--space-1)] text-[length:var(--text-caption)] font-semibold text-[var(--color-text)]',
  performanceCalendarDay: 'font-semibold text-[var(--color-text-main)]',
  performanceCalendarDayDetail: 'mt-[var(--space-4)] p-[var(--space-3)] bg-[var(--color-surface-elevated)] [border-radius:8px] [border:1px solid var(--color-border)]',
  performanceCalendarDayDetailClose: 'p-[0 var(--space-1)] [min-width:28px] [font-size:1.25rem] [line-height:1]',
  performanceCalendarDayDetailSubtitle: 'm-[var(--space-3) 0 var(--space-1)] text-[length:var(--text-caption)] font-semibold text-[var(--color-text-muted)]',
  performanceCalendarDayDetailTitle: 'flex items-center justify-between gap-[var(--space-2)] m-[0 0 var(--space-2)] text-[length:var(--text-body)] font-semibold',
  performanceCalendarDow: '[aspect-ratio:auto] p-[var(--space-1)]',
  performanceCalendarExecIdWrap: 'inline-flex flex-wrap items-center [gap:0.15rem]',
  performanceCalendarGrid: 'flex flex-col [gap:2px] w-full [max-width:none] m-0',
  performanceCalendarHeader: 'text-[length:var(--text-caption)] font-semibold text-[var(--color-text-muted)]',
  performanceCalendarLeft: '[flex:3 1 0] [min-width:min(100%, 280px)]',
  performanceCalendarLegendItemNotional: 'text-[var(--color-text-dim)]',
  performanceCalendarPnlLines: 'flex flex-col items-center [gap:0] [margin-top:2px] [line-height:1.2] [min-height:0] overflow-hidden',
  performanceCalendarPnlTypeTabs: 'mb-[var(--space-2)]',
  performanceCalendarRow: 'grid [grid-template-columns:repeat(7, 1fr)] [gap:2px]',
  performanceCalendarSection: 'mt-[var(--space-4)]',
  performanceCalendarStkDayDetail: 'mt-[var(--space-2)]',
  performanceCalendarSummary: '[flex:2 1 0] min-w-0',
  performanceCalendarSymbolPanel: '[margin-top:0]',
  performanceCalendarSymbolTabs: 'flex-wrap',
  performanceCalendarTabCount: 'ml-[var(--space-1)] [font-weight:400] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  performanceCalendarTabSum: 'ml-[var(--space-2)] tabular-nums font-semibold',
  performanceCalendarTitle: 'font-semibold [min-width:160px] text-center',
  performanceCalendarTotalUnrealized: 'mb-[var(--space-2)] text-[length:var(--text-caption)]',
  performanceSummaryEmpty: '[font-size:0.8125rem] m-0',
  performanceSummaryMetric: 'flex flex-col [gap:2px]',
  performanceSummaryMetricLabel: '[font-size:0.7rem] uppercase [letter-spacing:0.04em] text-[var(--color-text-muted)] [line-height:1.2]',
  performanceSummaryMetrics: 'grid [grid-template-columns:repeat(auto-fill, minmax(72px, 1fr))] gap-[var(--space-2) var(--space-3)] [flex:1] min-w-0 tabular-nums',
  performanceSummaryMetricValue: '[font-size:0.8125rem] font-semibold text-[var(--color-text-main)] [line-height:1.3]',
  performanceSummaryRow: 'flex items-start gap-[var(--space-3)] p-[var(--space-2) 0] [border-bottom:1px solid var(--color-border)] [font-size:0.8125rem]',
  performanceSummaryType: 'font-semibold shrink-0 [width:4.5rem] text-[var(--color-text-main)] [padding-top:2px]',
  pnlNegative: 'text-[var(--color-danger)]',
  posCompChartColSpan4: '[grid-column:span 4] min-w-0',
  posCompCoverageCharts: 'w-full [max-width:100%] [box-sizing:border-box]',
  realtimeQuoteDragHandle: '[cursor:grab] select-none [margin-right:0.3em] [opacity:0.25] [display:inline-block] align-middle [font-size:0.85em]',
  realtimeQuotesCardHeaderActions: 'flex items-center [gap:0.5rem] shrink-0 [margin-left:auto]',
  realtimeQuotesTable: 'w-full [min-width:320px] [table-layout:fixed]',
  realtimeStreamFilter: 'flex items-center gap-[var(--space-2)] flex-wrap',
  realtimeStreamFilterPills: 'inline-flex items-center [gap:4px] flex-wrap',
  realtimeStreamFiltersInline: 'flex flex-wrap items-center gap-[var(--space-2) var(--space-3)] [flex:1 1 auto] min-w-0',
  refOverviewCoverageMuted: 'text-[var(--color-text-muted)]',
  refOverviewCoverageSep: 'text-[var(--color-text-muted)] select-none',
  refOverviewCoverageStrip: 'flex flex-wrap items-baseline [gap:0.35rem 0.5rem] mt-[var(--space-2)] text-[length:var(--font-size-sm)] [line-height:1.4]',
  refOverviewCoverageTotal: 'text-[var(--color-text-muted)]',
  riskPayoffChartAxisLabel: '[font-size:8.5px] font-semibold [font-family:var(--font-sans), system-ui, sans-serif] [fill:var(--risk-payoff-axis)]',
  riskPayoffChartData: '[font-size:0.65rem] text-[var(--color-text-dim, #8b95a5)] tabular-nums',
  riskPayoffChartHead: 'flex flex-wrap items-baseline [gap:0.25rem 0.45rem] [margin-bottom:0]',
  riskPayoffChartHelpPanel: 'absolute [top:100%] [left:0] [right:0] [z-index:20] [margin-top:0.2rem] [padding:0.45rem 0.55rem] [font-size:0.65rem] [line-height:1.4] text-[var(--color-text-muted, #8b95a5)] bg-[var(--color-surface-elevated, rgba(28, 32, 40, 0.98))] [border:1px solid var(--color-border-subtle, rgba(255, 255, 255, 0.1))] [border-radius:6px] shadow-[0 4px 14px rgba(0, 0, 0, 0.35)]',
  riskPayoffChartHelpPanelP: 'm-0',
  riskPayoffChartHelpWrap: 'relative w-full [margin-bottom:0.3rem]',
  riskPayoffChartSub: '[font-size:0.65rem] text-[var(--color-text-muted, #8b95a5)] tabular-nums',
  riskPayoffChartSvg: 'block [max-width:100%] [border-radius:8px] [box-shadow:var(--risk-payoff-shadow)] [border:1px solid var(--risk-payoff-plot-border)]',
  riskPayoffChartTick: '[font-size:8px] [font-family:var(--font-mono), ui-monospace, monospace] tabular-nums [fill:var(--risk-payoff-tick)]',
  riskPayoffChartTitle: '[font-size:0.7rem] font-semibold uppercase [letter-spacing:0.04em] text-[var(--color-text-muted, #7a8492)]',
  riskProfileSection: '[overflow:visible]',
  riskProfileWarn: 'text-[#fbbf24]',
  riskScenarioMatrixNa: 'text-[var(--color-text-muted, #6b7280)] [font-size:0.75rem]',
  riskScenarioMatrixNum: 'text-right',
  riskValueGain: 'text-[#4ade80] font-semibold tabular-nums',
  riskValueLoss: 'text-[#f87171] font-semibold tabular-nums',
  riskValueUnlimited: '[letter-spacing:0.02em]',
  row: 'flex items-center mb-[var(--space-2)]',
  sectionDesc: '[font-weight:400] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  sectionHint: 'text-[length:var(--text-caption)] text-[var(--color-text-muted)] m-[var(--space-1) 0 0 0]',
  settingsIbPreferenceControls: 'flex flex-wrap gap-[var(--space-4)] items-center [margin-top:0]',
  settingsIbPreferenceRangeRow: 'inline-flex items-center gap-[var(--space-2)]',
  settingsIbRangeSuffix: '[margin-left:0.35rem] text-[var(--color-text-dim)] text-[length:var(--text-caption)]',
  settingsIbSection: '[margin-bottom:0]',
  statusPageMsg: 'text-[length:var(--text-small)]',
  strategyActiveNames: '[font-size:0.8125rem] text-[var(--color-text-muted)] flex flex-col [gap:0.125rem]',
  strategyActiveNamesCompact: 'flex-row flex-wrap items-baseline [gap:0.35rem 0.65rem] [font-size:0.6875rem] [margin-top:0.15rem] [line-height:1.2]',
  strategyCompactControls: '[margin-top:0]',
  strategyCompactHeader: 'flex items-center gap-[var(--space-2)] mb-[var(--space-1)]',
  strategyCompactLabel: 'text-[var(--color-text-muted)]',
  strategyCompactStatus: '[font-size:0.75rem] text-[var(--color-text-muted)] mb-[var(--space-2)] [line-height:1.25]',
  strategyCompactStatusBlocks: 'font-medium text-[var(--color-text-muted)]',
  strategyCompactStatusK: 'font-semibold text-[var(--color-text-main)]',
  strategyCompactSummary: 'flex flex-wrap gap-[var(--space-1) var(--space-3)] [font-size:0.75rem] mb-[var(--space-2)]',
  strategyCompactSummaryInline: '[flex:2 1 14rem] min-w-0 [margin-bottom:0] [gap:0] [row-gap:0.2rem] [column-gap:0] [font-size:0.6875rem] [line-height:1.25] items-baseline',
  strategyCompactSummaryItem: 'inline-flex gap-[var(--space-1)]',
  strategyCompactTitle: '[font-size:0.9375rem] font-semibold text-[var(--color-text-main)]',
  strategyControlsPrimaryRow: 'flex flex-wrap items-center gap-[var(--space-2)]',
  strategyEmergencyBar: 'flex items-center justify-between gap-[var(--space-3)] mt-[var(--space-3)] [padding-top:var(--space-3)] [border-top:1px solid var(--color-border)]',
  strategyEmergencyBarLabel: 'inline-flex items-center gap-[var(--space-1)] [font-size:0.6875rem] font-bold uppercase [letter-spacing:0.05em] text-[var(--color-text-muted)]',
  strategyFlattenEmergencyBtn: 'inline-flex items-center justify-center [width:40px] [height:40px] p-0 shrink-0 [border:2px solid var(--color-danger)] [border-radius:10px] bg-[var(--color-danger-soft)] text-[var(--color-danger)] cursor-pointer',
  strategyFullMetaPrimary: '[flex:1 1 12rem] min-w-0 text-[length:var(--text-body)] [line-height:1.35]',
  strategyFullMetaRow: 'flex flex-wrap items-baseline gap-[var(--space-2) var(--space-4)] mb-[var(--space-2)]',
  strategyOppComboboxInput: 'w-full [cursor:text] [text-overflow:ellipsis]',
  strategyWinRateMetricValueMuted: 'text-[var(--color-text-dim)] font-medium',
  structureCopyTemplateSelect: '[max-width:100%] w-full mt-[var(--space-2)]',
  structureDetailsAddConstraint: '[align-self:flex-start] [margin-top:0] p-[2px var(--space-2)] [font-size:0.8125rem]',
  structureDetailsConstraintInt: '[width:3.5rem] p-[var(--space-1) var(--space-2)] [font-size:0.8125rem]',
  structureDetailsConstraintRemove: '[margin-left:auto] shrink-0 p-[2px var(--space-2)] [font-size:0.8125rem]',
  structureDetailsConstraintRow: 'flex flex-wrap items-center gap-[var(--space-1)] p-[var(--space-1) var(--space-2)] [border-radius:4px] [border:1px solid transparent] bg-[var(--color-surface)]',
  structureDetailsConstraints: 'flex flex-col gap-[var(--space-1)]',
  structureDetailsConstraintType: '[width:8rem] [min-width:6rem] p-[var(--space-1) var(--space-2)] [font-size:0.8125rem]',
  structureDetailsConstraintValue: '[width:6rem] [min-width:5rem] p-[var(--space-1) var(--space-2)] [font-size:0.8125rem]',
  structureDetailsFieldAvailable: '[align-self:center] [padding-bottom:2px]',
  structureDetailsHint: '[font-size:0.75rem] text-[var(--color-text-muted)] m-0 [line-height:1.35]',
  structureDetailsInput: 'p-[var(--space-1) var(--space-2)] [border:1px solid var(--color-border)] [border-radius:4px] bg-[var(--color-surface)] text-[var(--color-text-main)] font-[inherit] [font-size:0.875rem]',
  structureDetailsInputNarrow: '[max-width:6rem]',
  structureDetailsMetaGrid: 'grid [grid-template-columns:1fr minmax(5rem, 6rem) auto] gap-[var(--space-2) var(--space-4)] [align-items:end]',
  structureDetailsPanel: 'min-w-0 p-[var(--space-3) var(--space-4)] [border-radius:8px] [border:1px solid var(--color-border)] [border-left:3px solid var(--color-accent)] bg-[var(--color-surface)] shadow-[0 1px 4px rgba(0, 0, 0, 0.08)]',
  structureDetailsPanelDesc: 'mb-[var(--space-2)] [font-size:0.8125rem]',
  structureDetailsPanelSpan2: '[grid-column:1]',
  structureDetailsPanelTitle: 'text-[length:var(--text-caption, 0.875rem)] font-semibold text-[var(--color-accent)] m-[0 0 var(--space-2) 0] [padding-bottom:var(--space-2)] [border-bottom:1px solid var(--color-border)] [letter-spacing:0.03em] uppercase',
  structureDetailsParamRow: 'flex items-center gap-[var(--space-1)] flex-wrap',
  structureDetailsParams: 'flex flex-wrap gap-[var(--space-2) var(--space-4)] [align-items:flex-end]',
  structureDetailsTable: 'w-full border-collapse [font-size:0.8125rem]',
  structureDetailsTableWrap: 'overflow-x-auto [border-radius:4px] [border:1px solid var(--color-border)] bg-[var(--color-surface)]',
  structureDetailsToggle: 'inline-flex items-center gap-[var(--space-1)]',
  structureFormBody: 'p-[var(--space-4) var(--space-5)]',
  structureFormFooter: 'flex items-center justify-end gap-[var(--space-3)] p-[var(--space-3) var(--space-5)] [border-top:1px solid var(--color-border)] bg-[var(--color-surface)]',
  structureFormHeaderBadge: '[display:inline-block] ml-[var(--space-2)] [padding:1px 8px] text-[length:var(--text-tiny)] font-semibold [border-radius:4px] bg-[var(--color-accent-soft)] text-[var(--color-accent)] align-middle [letter-spacing:0.02em]',
  structureFormHeaderClose: 'flex items-center justify-center [width:2rem] [height:2rem] [border-radius:6px] [border:1px solid transparent] [background:transparent] text-[var(--color-text-muted)] [font-size:1.25rem] [line-height:1] cursor-pointer',
  structureParamExample: 'text-[length:var(--text-caption)] text-[var(--color-text-muted)] p-[var(--space-2) var(--space-3)] [border-radius:6px] bg-[rgba(255, 255, 255, 0.03)] [border:1px solid var(--color-border)] mb-[var(--space-3)]',
  structureTemplateFilterDim: 'flex flex-col [gap:4px]',
  structureTemplateFilterDimLabel: 'text-[length:var(--text-tiny)] font-semibold text-[var(--color-text-muted)] uppercase [letter-spacing:0.03em]',
  structureTemplateFiltersCompact: 'mb-[var(--space-2)] p-[var(--space-2)]',
  structureTemplateFiltersDims: 'grid [grid-template-columns:repeat(auto-fill, minmax(140px, 1fr))] gap-[var(--space-2)] mt-[var(--space-3)]',
  structureTemplateFilterSelect: 'w-full text-[length:var(--text-caption)]',
  structureTemplateFiltersEmptyHint: 'text-[var(--color-text-muted)]',
  structureTemplateFiltersMeta: 'm-[var(--space-2) 0 0] text-[length:var(--text-caption)] text-[var(--color-text-dim)]',
  structureTemplateFiltersSearch: '[flex:1] [min-width:12rem] [max-width:24rem]',
  structureTemplateFiltersSearchRow: 'flex flex-wrap gap-[var(--space-2)] items-center',
  structureTemplateGridEmpty: '[grid-column:1 / -1] m-0 p-[var(--space-4)] text-center text-[var(--color-text-muted)] text-[length:var(--text-body)]',
  structureTemplatePanelCode: 'text-[length:var(--text-tiny)] [font-family:var(--font-mono, ui-monospace, monospace)] text-[var(--color-text-dim)]',
  structureTemplatePanelDesc: 'text-[length:var(--text-caption)] text-[var(--color-text-muted)] [line-height:1.45] [display:-webkit-box] [-webkit-line-clamp:2] [-webkit-box-orient:vertical] overflow-hidden',
  structureTemplatePanelName: 'text-[length:var(--text-body)] font-semibold text-[var(--color-text-main)] [line-height:1.3]',
  structureTemplatePanelSelected: 'border-[var(--color-accent)] bg-[var(--color-accent-soft)] [box-shadow:0 0 0 1px var(--color-accent), 0 4px 12px rgba(163, 230, 53, 0.08)]',
  structureTemplatePanelTag: '[display:inline-block] [padding:1px 7px] text-[length:var(--text-tiny)] font-medium [border-radius:3px] bg-[rgba(255, 255, 255, 0.06)] text-[var(--color-text-dim)] [text-transform:capitalize]',
  structureTemplatePanelTags: 'flex flex-wrap [gap:4px] [margin-top:2px]',
  structureWizardStep: 'mb-[var(--space-3)]',
  structureWizardStepCircle: '[width:2.25rem] [height:2.25rem] [border-radius:50%] flex items-center justify-center [font-size:0.875rem] font-semibold [border:2px solid var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text-muted)] shrink-0',
  structureWizardStepConnector: '[flex:1] [min-width:1.5rem] [height:2px] m-[0 var(--space-1)] bg-[var(--color-border)] [align-self:center]',
  structureWizardStepHead: 'flex items-center w-full [justify-content:flex-start]',
  structureWizardStepItemLast: '[flex:0 0 auto]',
  structureWizardStepLabel: 'mt-[var(--space-2)] text-[length:var(--text-caption, 0.875rem)] text-[var(--color-text-muted)] text-center [line-height:1.3]',
  systemTabPanel: '[min-height:120px]',
  systemTabs: 'flex [gap:0] mb-[var(--space-4)] [border-bottom:1px solid var(--color-border)]',
  tableOperations: '[border-radius:8px] overflow-hidden',
  toggleSwitchCaption: '[opacity:0.9]',
  tradeLedgerAddJournalBtnIcon: 'shrink-0 [opacity:0.92]',
  underlyingCoverageAccount: '[font-family:var(--font-mono, \'JetBrains Mono\', monospace)] [font-size:0.82em] text-[var(--color-text-main, #e4e9ef)]',
  watchlistToggleSwitchThumb: 'absolute [top:2px] [left:2px] [width:22px] [height:22px] bg-[#fff] [border-radius:50%] shadow-[0 1px 3px rgba(0, 0, 0, 0.3)]',
  watchlistToggleSwitchTrack: 'absolute [inset:0] bg-[var(--color-border-strong)] [border-radius:13px]',
} as const

export function w9Cn(...parts: Array<string | false | null | undefined>) {
  return cn(...parts)
}
