import { cn } from '@/lib/utils'

/** Auto-migrated from legacy CSS — Phase 7 Wave 6 */
export const rj = {
  activePill: 'text-[length:var(--font-size-sm)] font-semibold text-[var(--color-text-muted)] [padding:0.2rem 0.5rem] [border-radius:999px] [border:1px solid var(--color-border)] bg-[color-mix(in srgb, var(--color-text-muted) 8%, transparent)] text-[length:var(--font-size-sm)] font-semibold text-[var(--color-text-muted)] [padding:0.2rem 0.5rem] [border-radius:999px] [border:1px solid var(--color-border)] bg-[color-mix(in srgb, var(--color-text-muted) 8%, transparent)]',
  catalogActionCell: 'text-center [width:1%] whitespace-nowrap align-middle text-center [width:1%] whitespace-nowrap align-middle',
  catalogApiLink: 'text-[var(--color-link, var(--color-accent))] text-[length:var(--font-size-sm)] underline [text-underline-offset:2px] text-[var(--color-link, var(--color-accent))] text-[length:var(--font-size-sm)] underline [text-underline-offset:2px]',
  catalogCaption: '[caption-side:top] text-left text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [padding-bottom:var(--space-2)] [caption-side:top] text-left text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [padding-bottom:var(--space-2)]',
  catalogCellStrong: 'font-semibold font-semibold',
  catalogCode: 'text-[length:var(--font-size-sm)] break-words text-[length:var(--font-size-sm)] break-words',
  catalogColAction: '[width:10%] [width:10%]',
  catalogColJob: '[width:12%] [width:12%]',
  catalogColPgBiz: '[width:16%] [width:16%]',
  catalogColPgJob: '[width:16%] [width:16%]',
  catalogColQueue: '[width:26%] [width:26%]',
  catalogColRest: '[width:20%] [width:20%]',
  catalogEnqueueBtn: 'inline-flex items-center justify-center [width:2.25rem] [height:2.25rem] [min-height:0] p-0 rounded-[var(--radius-md, 6px)] [box-shadow:0 1px 2px color-mix(in srgb, var(--color-accent) 25%, transparent)] inline-flex items-center justify-center [width:2.25rem] [height:2.25rem] [min-height:0] p-0 rounded-[var(--radius-md, 6px)] [box-shadow:0 1px 2px color-mix(in srgb, var(--color-accent) 25%, transparent)]',
  catalogJobCell: 'flex items-start flex-nowrap gap-[var(--space-1)] flex items-start flex-nowrap gap-[var(--space-1)]',
  catalogJobName: 'min-w-0 min-w-0',
  catalogPgEmpty: 'text-[var(--color-text-muted)] text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] text-[length:var(--font-size-sm)]',
  catalogPgNames: 'whitespace-normal break-words whitespace-normal break-words',
  catalogQueueCell: 'whitespace-normal break-words whitespace-normal break-words',
  catalogQueueLink: 'no-underline [color:inherit] no-underline [color:inherit]',
  catalogRest: 'whitespace-normal break-words whitespace-normal break-words',
  catalogSectionHead: 'mb-[var(--space-2)] mb-[var(--space-2)]',
  catalogSectionMeta: 'm-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.45] m-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.45]',
  catalogSectionTitle: 'm-[0 0 var(--space-1)] text-[length:var(--font-size-base, 1rem)] font-semibold m-[0 0 var(--space-1)] text-[length:var(--font-size-base, 1rem)] font-semibold',
  catalogSymbols: 'mb-[var(--space-3)] mb-[var(--space-3)]',
  catalogTable: '[table-layout:fixed] w-full [min-width:52rem] border-collapse text-[length:var(--font-size-sm)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] overflow-hidden [table-layout:fixed] w-full [min-width:52rem] border-collapse text-[length:var(--font-size-sm)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] overflow-hidden',
  catalogTableSep: 'text-[var(--color-text-muted)] select-none text-[var(--color-text-muted)] select-none',
  catalogTdPg: '[line-height:1.45] align-top [line-height:1.45] align-top',
  catalogTdPgJob: '[border-left:1px solid var(--color-border)] [border-left:1px solid var(--color-border)]',
  catalogThAction: '[width:2.75rem] [width:2.75rem]',
  catalogThPgGroup: 'text-center align-middle text-center align-middle',
  catalogThPgSub: 'text-[length:var(--text-caption, 0.7rem)] font-semibold uppercase [letter-spacing:0.04em] text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-text-muted) 8%, transparent)] text-[length:var(--text-caption, 0.7rem)] font-semibold uppercase [letter-spacing:0.04em] text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-text-muted) 8%, transparent)]',
  catalogWrap: 'overflow-x-auto mt-[var(--space-2)] [-webkit-overflow-scrolling:touch] overflow-x-auto mt-[var(--space-2)] [-webkit-overflow-scrolling:touch]',
  mdActions: 'flex flex-wrap gap-[var(--space-2)] items-center mt-[var(--space-2)] flex flex-wrap gap-[var(--space-2)] items-center mt-[var(--space-2)]',
  mdEnqueueActions: '[flex:0 0 auto] flex items-center [flex:0 0 auto] flex items-center',
  mdEnqueueActionsStack: 'flex flex-col gap-[var(--space-2)] items-stretch flex flex-col gap-[var(--space-2)] items-stretch',
  mdEnqueueFields: '[flex:1 1 12rem] min-w-0 [flex:1 1 12rem] min-w-0',
  mdEnqueueHint: 'm-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.4] m-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.4]',
  mdMeta: 'flex flex-col gap-[var(--space-2)] mb-[var(--space-3)] [padding-bottom:var(--space-3)] [border-bottom:1px solid var(--color-border)] text-[length:var(--font-size-sm)] flex flex-col gap-[var(--space-2)] mb-[var(--space-3)] [padding-bottom:var(--space-3)] [border-bottom:1px solid var(--color-border)] text-[length:var(--font-size-sm)]',
  mdMetaLabel: 'text-[var(--color-text-muted)] font-medium [min-width:4.5rem] text-[var(--color-text-muted)] font-medium [min-width:4.5rem]',
  mdMetaRow: 'flex flex-wrap gap-[var(--space-1) var(--space-3)] items-baseline flex flex-wrap gap-[var(--space-1) var(--space-3)] items-baseline',
  mdNav: 'list-none m-0 p-0 flex flex-col gap-[var(--space-1)] flex-row flex-wrap [align-items:flex-end] [gap:0.15rem] p-0 [border-bottom:1px solid var(--color-border)] list-none m-0 p-0 flex flex-col gap-[var(--space-1)]',
  mdNavItem: 'm-0 m-0',
  mdPanel: 'min-w-0 [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] p-[var(--space-3)] bg-[color-mix(in srgb, var(--color-text-muted) 4%, transparent)] [margin-top:0] [border-top-left-radius:0] [border-top-right-radius:var(--radius-md, 6px)] min-w-0 [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] p-[var(--space-3)] bg-[color-mix(in srgb, var(--color-text-muted) 4%, transparent)]',
  mdSectionTitle: 'm-[0 0 var(--space-2)] text-[length:var(--font-size-sm)] font-semibold text-[var(--color-text-muted)] uppercase [letter-spacing:0.03em] m-[0 0 var(--space-2)] text-[length:var(--font-size-sm)] font-semibold text-[var(--color-text-muted)] uppercase [letter-spacing:0.03em]',
  mdTab: 'w-full text-left [padding:0.45rem 0.65rem] rounded-[var(--radius-md, 6px)] [border:1px solid var(--color-border)] bg-[var(--color-surface, var(--color-bg-elevated))] text-[var(--color-text-main)] text-[length:var(--font-size-sm)] font-medium cursor-pointer [width:auto] text-center [padding:0.5rem 0.85rem] [margin-bottom:-1px] rounded-[var(--radius-md, 6px) var(--radius-md, 6px) 0 0] [border:1px solid transparent] [border-bottom-color:transparent] w-full text-left [padding:0.45rem 0.65rem] rounded-[var(--radius-md, 6px)] [border:1px solid var(--color-border)] bg-[var(--color-surface, var(--color-bg-elevated))] text-[var(--color-text-main)] text-[length:var(--font-size-sm)] font-medium cursor-pointer',
  sheet: '[width:min(28rem, 100vw)] [max-width:100%] bg-[var(--color-bg, var(--color-surface))] [border-left:1px solid var(--color-border)] p-[var(--space-4)] overflow-y-auto shadow-[-4px 0 24px rgba(0, 0, 0, 0.15)] [outline:none] [width:min(28rem, 100vw)] [max-width:100%] bg-[var(--color-bg, var(--color-surface))] [border-left:1px solid var(--color-border)] p-[var(--space-4)] overflow-y-auto shadow-[-4px 0 24px rgba(0, 0, 0, 0.15)] [outline:none]',
  sheetBadge: 'text-[length:var(--text-caption, 0.7rem)] font-semibold uppercase [letter-spacing:0.04em] text-[var(--color-text-muted)] [border:1px solid var(--color-border)] [padding:0.1rem 0.35rem] [border-radius:4px] text-[length:var(--text-caption, 0.7rem)] font-semibold uppercase [letter-spacing:0.04em] text-[var(--color-text-muted)] [border:1px solid var(--color-border)] [padding:0.1rem 0.35rem] [border-radius:4px]',
  sheetDetails: 'mt-[var(--space-2)] mt-[var(--space-2)]',
  sheetEmpty: 'm-0 p-[var(--space-4) 0] text-[var(--color-text-muted)] text-[length:var(--font-size-sm)] text-center m-0 p-[var(--space-4)] text-center m-0 p-[var(--space-4) 0] text-[var(--color-text-muted)] text-[length:var(--font-size-sm)] text-center',
  sheetErr: 'm-[0 0 var(--space-2) !important] text-[length:var(--font-size-sm)] m-[0 0 var(--space-2) !important] text-[length:var(--font-size-sm)]',
  sheetFooter: 'mt-[var(--space-4)] [padding-top:var(--space-3)] [border-top:1px solid var(--color-border)] shrink-0 mt-[var(--space-4)] [padding-top:var(--space-3)] [border-top:1px solid var(--color-border)]',
  sheetFooterHint: 'm-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.5] m-0 text-[length:var(--font-size-sm)] text-[var(--color-text-muted)] [line-height:1.5]',
  sheetHeader: 'flex items-center justify-between gap-[var(--space-2)] mb-[var(--space-2)] flex items-center justify-between gap-[var(--space-2)] mb-[var(--space-2)]',
  sheetJobId: 'text-[length:var(--font-size-sm)] break-all text-[length:var(--font-size-sm)] break-all',
  sheetKind: 'font-semibold text-[length:var(--font-size-sm)] font-semibold text-[length:var(--font-size-sm)]',
  sheetLink: '[display:inline] p-0 border-0 bg-none text-[var(--color-link, var(--color-accent))] font-[inherit] cursor-pointer underline [text-underline-offset:2px] [display:inline] p-0 border-0 bg-none text-[var(--color-link, var(--color-accent))] font-[inherit] cursor-pointer underline [text-underline-offset:2px]',
  sheetList: 'flex flex-col gap-[var(--space-3)] [max-height:min(60vh, 28rem)] overflow-y-auto [padding-right:var(--space-1)] flex flex-col gap-[var(--space-3)] [max-height:min(60vh, 28rem)] overflow-y-auto [padding-right:var(--space-1)]',
  sheetMeta: 'm-[0 0 var(--space-3)] text-[length:var(--font-size-sm, 0.875rem)] text-[var(--color-text-muted)] [line-height:1.45] shrink-0 m-[0 0 var(--space-3)] text-[length:var(--font-size-sm, 0.875rem)] text-[var(--color-text-muted)] [line-height:1.45]',
  sheetRow: 'p-[var(--space-3)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] bg-[var(--color-surface-elevated, var(--color-bg))] p-[var(--space-3)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] bg-[var(--color-surface-elevated, var(--color-bg))]',
  sheetRowHead: 'flex flex-wrap items-center gap-[var(--space-2)] mb-[var(--space-2)] flex flex-wrap items-center gap-[var(--space-2)] mb-[var(--space-2)]',
  sheetRowId: 'flex flex-wrap items-center gap-[var(--space-2)] mb-[var(--space-2)] flex flex-wrap items-center gap-[var(--space-2)] mb-[var(--space-2)]',
  sheetStatus: 'text-[length:var(--text-caption, 0.75rem)] font-semibold lowercase [padding:0.15rem 0.45rem] [border-radius:4px] text-[length:var(--text-caption, 0.75rem)] font-semibold lowercase [padding:0.15rem 0.45rem] [border-radius:4px]',
  sheetStatusErr: 'text-[var(--color-danger, #c00)] bg-[color-mix(in srgb, var(--color-danger, #c00) 12%, transparent)] text-[var(--color-danger, #c00)] bg-[color-mix(in srgb, var(--color-danger, #c00) 12%, transparent)]',
  sheetStatusOk: 'text-[var(--color-success, green)] bg-[color-mix(in srgb, var(--color-success, green) 12%, transparent)] text-[var(--color-success, green)] bg-[color-mix(in srgb, var(--color-success, green) 12%, transparent)]',
  sheetStatusRun: 'text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-text-muted) 14%, transparent)] text-[var(--color-text-muted)] bg-[color-mix(in srgb, var(--color-text-muted) 14%, transparent)]',
  sheetSummary: 'm-[0 0 var(--space-2)] text-[length:var(--font-size-sm)] [line-height:1.45] m-[0 0 var(--space-2)] text-[length:var(--font-size-sm)] [line-height:1.45]',
  sheetTableWrap: '[max-height:min(60vh, 32rem)] overflow-auto mb-[var(--space-2)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] bg-[var(--color-surface-elevated, var(--color-bg))] [flex:1 1 auto] [min-height:0] [max-height:none] overflow-auto [margin-bottom:0] [max-height:min(60vh, 32rem)] overflow-auto mb-[var(--space-2)] [border:1px solid var(--color-border)] rounded-[var(--radius-md, 6px)] bg-[var(--color-surface-elevated, var(--color-bg))]',
  sheetTitle: 'm-0 text-[length:var(--text-h3, 1.1rem)] m-0 text-[length:var(--text-h3, 1.1rem)]',
  sheetToolbar: 'flex flex-wrap gap-[var(--space-2)] mb-[var(--space-3)] shrink-0 flex flex-wrap gap-[var(--space-2)] mb-[var(--space-3)]',
  table: 'w-full [min-width:40rem] border-collapse text-[length:var(--font-size-sm)] w-full [min-width:40rem] border-collapse text-[length:var(--font-size-sm)]',
  tableCopy: 'mt-[var(--space-1)] mt-[var(--space-1)]',
  tableDash: 'text-[var(--color-text-muted)] text-[var(--color-text-muted)]',
  tableDedup: 'text-center tabular-nums text-center tabular-nums',
  tableDetailsCell: '[max-width:10rem] [max-width:10rem]',
  tableIdCell: '[max-width:11rem] [max-width:11rem]',
  tableJobId: 'block text-[length:var(--font-size-sm)] break-all block text-[length:var(--font-size-sm)] break-all',
  tableKind: 'font-semibold whitespace-nowrap font-semibold whitespace-nowrap',
  tableStreamErr: 'm-[var(--space-1) 0 0] text-[length:var(--text-caption, 0.75rem)] text-[var(--color-danger, #c00)] [line-height:1.35] m-[var(--space-1) 0 0] text-[length:var(--text-caption, 0.75rem)] text-[var(--color-danger, #c00)] [line-height:1.35]',
  tableSummary: '[max-width:14rem] [line-height:1.4] break-words [max-width:14rem] [line-height:1.4] break-words',
  tableTime: 'whitespace-nowrap tabular-nums whitespace-nowrap tabular-nums',
  tableRow: '',
  sheetBackdrop:
    'fixed inset-0 z-[200] flex items-stretch justify-end bg-[rgba(0,0,0,0.45)]',
  sheetBackdropNested: 'z-[220]',
  sheetWide: 'w-[min(44rem,100vw)]',
  sheetBody: '',
  sheetMetaSub:
    'mt-[0.35rem] text-[length:var(--text-caption)] text-[var(--color-text-muted)]',
  sheetMetaWarn:
    'mt-[0.35rem] text-[length:var(--text-caption)] text-[var(--color-warning-strong,#b8860b)]',
  md: 'mt-[var(--space-2)] grid grid-cols-1 items-start gap-[var(--space-3)] min-[52rem]:grid-cols-[minmax(11rem,14rem)_1fr]',
  mdTabs: 'flex flex-col items-stretch gap-0',
  mdEnqueueRow:
    'flex flex-wrap items-center justify-between gap-x-[var(--space-3)] gap-y-[var(--space-2)]',
  mdEnqueueBtn: 'inline-flex items-center whitespace-nowrap',
} as const

export function rjCn(...parts: Array<string | false | null | undefined>) {
  return cn(...parts)
}
