import { cn } from '@/lib/utils'

/** Auto-migrated from sdp-*.css — Phase 7 Wave 4 */
export const SDP = {
  actionsCard: 'bg-card border border-border rounded-[12px] [margin-bottom:var(--space-5)]',
  actionsTitle: 'font-bold uppercase text-muted-foreground',
  btnBackfillSelected: 'inline-flex p-[0.3125rem var(--space-3)] rounded-[6px] font-bold',
  btnCheck: 'inline-flex p-[0.4rem var(--space-3)] rounded-[5px] font-semibold',
  btnCheckSky: 'inline-flex p-[0.4rem var(--space-3)] rounded-[5px] font-semibold',
  btnCopyLlm: 'inline-flex p-[0.3125rem var(--space-3)] rounded-[6px] font-semibold',
  btnCopyLlmErr: 'text-muted-foreground',
  btnCopyLlmOk: 'text-muted-foreground',
  btnGaps: 'inline-flex p-[0.3125rem var(--space-3)] rounded-[6px] font-semibold border border-border text-muted-foreground',
  btnGapsOk: 'text-muted-foreground',
  btnGapsVoid: 'text-muted-foreground',
  btnGapsWarn: 'text-muted-foreground',
  btnGhost: 'inline-flex border-0 text-muted-foreground p-[0.45rem var(--space-2)] rounded-[4px]',
  btnPrimary: 'inline-flex gap-2 p-[0.45rem var(--space-4)] border-0 rounded-[5px] font-bold',
  btnReack: 'inline-flex text-muted-foreground',
  btnSecondary: 'inline-flex gap-2 p-[0.45rem var(--space-3)] text-muted-foreground border border-border rounded-[5px]',
  btnVoidToggle: 'inline-flex text-muted-foreground',
  btnVoidToggleActive: 'text-muted-foreground',
  catalogBadge: 'inline-flex font-extrabold uppercase rounded-[3px] shrink-0',
  catalogBlock: '[margin-bottom:var(--space-5)]',
  catalogDesc: 'text-muted-foreground',
  catalogGrid: 'grid gap-3',
  catalogLoading: 'grid gap-3',
  catalogTab: 'inline-flex gap-2 p-[0.55rem var(--space-4)] border-0 [margin-bottom:-1px] text-muted-foreground',
  catalogTabActive: 'inline-flex gap-2 p-[0.55rem var(--space-4)] border-0 [margin-bottom:-1px] text-muted-foreground',
  catalogTabCount: 'border border-border rounded-[10px] text-muted-foreground',
  catalogTabTitle: 'font-semibold',
  catalogTabs: 'flex [margin-bottom:var(--space-3)]',
  checkDot: 'rounded-full shrink-0 box-border',
  checkDotLoading: 'rounded-full shrink-0 box-border',
  checkDotUnknown: 'rounded-full shrink-0 box-border',
  checkGap: 'inline-flex font-bold rounded-[3px] [margin-left:au]',
  checkGapError: 'text-muted-foreground',
  checkGapOk: 'text-muted-foreground',
  checkGapVoid: 'text-muted-foreground',
  checkGapWarn: 'text-muted-foreground',
  checkMeta: 'flex gap-3 [padding-left:calc(7px + var(--space-2))]',
  checkNote: 'text-muted-foreground [margin-left:au]',
  checkPrimary: 'font-semibold text-muted-foreground',
  checkPrimaryLabel: 'text-muted-foreground',
  checkRow: 'flex gap-2 min-w-0',
  checkSecondary: 'text-muted-foreground',
  checkStrip: 'flex p-[0.5rem var(--space-3)] rounded-[6px] border border-border',
  checkStripLoading: 'flex p-[0.5rem var(--space-3)] rounded-[6px] border border-border',
  checkStripNotchecked: 'opacity-[0.6]',
  checkTarget: 'text-muted-foreground',
  checkText: '',
  checkTextDim: 'text-muted-foreground',
  condDetail: 'bg-card border border-border rounded-[6px]',
  condDetailFormula: 'm-0 text-muted-foreground',
  condDetailKey: 'font-semibold text-muted-foreground uppercase',
  condDetailMeta: 'flex gap-1 [margin-bottom:var(--space-3)]',
  condDetailRow: 'grid gap-2 items-baseline',
  condDetailRowFormula: '[margin-top:4px]',
  condDetailVal: 'text-muted-foreground',
  condInfoBtn: 'shrink-0 border border-border rounded-full inline-flex text-muted-foreground p-0',
  condInfoBtnActive: 'shrink-0 border border-border rounded-full inline-flex text-muted-foreground p-0',
  condSqlBlock: 'border border-border rounded-[6px]',
  coverageBar: 'rounded-[999px]',
  coverageBarFill: 'block',
  coverageBarFillHigh: 'block',
  coverageBarFillLow: 'block',
  coverageBarFillMid: 'block',
  coverageBarFillUnknown: 'block',
  coverageCell: 'inline-flex gap-2',
  coverageNa: 'text-muted-foreground',
  coveragePct: 'font-bold text-muted-foreground',
  critColFields: '',
  critColStatus: '[padding-left:0.4re] [padding-right:0.2re]',
  critColStatusLabel: '',
  critCondition: '',
  critDot: 'inline-block rounded-full',
  critDotError: 'inline-block rounded-full',
  critDotOk: 'inline-block rounded-full',
  critDotUnknown: 'inline-block rounded-full',
  critDotWarn: 'inline-block rounded-full',
  critExplain: 'text-muted-foreground',
  critFieldChip: 'rounded-[3px] border border-border text-muted-foreground',
  critFieldChipBars: 'rounded-[3px] border border-border text-muted-foreground',
  critFields: 'flex',
  critName: 'font-semibold text-muted-foreground',
  critNote: 'block text-muted-foreground [margin-top:0.15re]',
  critRow: '',
  critStatusPill: 'inline-flex font-bold rounded-[3px]',
  criteriaBar: 'rounded-[3px] bg-card',
  criteriaBarFill: 'rounded-[3px]',
  criteriaBarFillError: 'rounded-[3px]',
  criteriaBarFillOk: 'rounded-[3px]',
  criteriaBarFillWarn: 'rounded-[3px]',
  criteriaGroup: 'rounded-[10px]',
  criteriaGroupBadge: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupBadgeFund: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupBadgeMomentum: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupBadgeSentiment: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupBadgeStructure: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupBadgeTech: 'inline-flex p-[0.15rem 0.55re] rounded-[4px] font-extrabold uppercase',
  criteriaGroupCount: '[margin-left:au] font-bold text-muted-foreground p-[0.1rem 0.5re] rounded-[6px] border border-border',
  criteriaGroupHead: 'flex gap-2 [margin-bottom:var(--space-1)]',
  criteriaGroupLabel: 'font-semibold text-muted-foreground',
  criteriaGroupSub: 'text-muted-foreground [margin-bottom:var(--space-3)]',
  criteriaGroups: 'flex gap-4',
  criteriaHeader: 'flex [margin-bottom:var(--space-4)]',
  criteriaHeaderLeft: 'flex gap-3',
  criteriaLabel: 'text-muted-foreground',
  criteriaOverall: 'inline-flex font-bold p-[0.2rem 0.65re] rounded-[99px]',
  criteriaRow: 'grid gap-2',
  criteriaRows: 'flex',
  criteriaSection: 'bg-card border border-border rounded-[12px] [margin-bottom:var(--space-5)]',
  criteriaStat: 'text-muted-foreground tabular-nums',
  criteriaTab: 'border border-border text-muted-foreground rounded-[999px] p-[0.35rem 0.8re] font-bold inline-flex',
  criteriaTabActive: 'text-muted-foreground',
  criteriaTabCount: 'opacity-[0.92]',
  criteriaTable: 'w-full border-collapse',
  criteriaTabs: 'inline-flex gap-2',
  criteriaTitle: 'font-bold text-muted-foreground',
  depChip: 'rounded-[3px] border border-border text-muted-foreground',
  dp: 'rounded-[3px] border border-border text-muted-foreground',
  dpsHeader: 'font-bold uppercase text-muted-foreground [margin-bottom:var(--space-2)]',
  dpsList: 'flex',
  dpsSection: '[padding-top:var(--space-3)]',
  drawer: 'flex bg-card',
  drawerOpen: 'flex bg-card',
  drawerWide: 'flex bg-card',
  drawerActions: 'flex gap-2 shrink-0',
  drawerBackdrop: '',
  drawerBadge: 'inline-flex p-[0.1rem var(--space-2)] rounded-[99px] font-bold text-muted-foreground',
  drawerBody: 'flex-1',
  drawerClose: 'rounded-[6px] flex text-muted-foreground',
  drawerEmpty: '',
  drawerError: 'text-muted-foreground',
  drawerHeader: 'flex shrink-0',
  drawerLoading: '',
  drawerReasons: 'flex gap-2 shrink-0',
  drawerSearch: 'flex gap-2 shrink-0',
  drawerSearchClear: 'rounded-[4px] flex text-muted-foreground border-0',
  drawerSearchCount: 'text-muted-foreground',
  drawerSearchInput: 'flex-1 min-w-0 p-[0.3125rem var(--space-3)] border border-border rounded-[6px] text-muted-foreground outline-none',
  drawerSub: 'text-muted-foreground shrink-0',
  drawerTitle: 'flex gap-2 font-bold text-muted-foreground',
  drawerTitleIcon: 'text-muted-foreground',
  drawerTruncated: 'text-muted-foreground shrink-0',
  drawerTruncatedActions: 'flex gap-3',
  evalBarDist: '',
  evalBody: 'flex gap-4',
  evalCol: 'flex gap-3 min-w-0',
  evalCols: 'grid',
  evalCombined: 'flex gap-2 bg-card',
  evalCombinedLabel: 'text-muted-foreground',
  evalCombinedSep: 'text-muted-foreground',
  evalDistChip: 'bg-card text-muted-foreground',
  evalDistChipWarn: 'text-muted-foreground',
  evalFailureReasons: '',
  evalPanel: 'border border-border bg-card',
  evalSection: 'flex gap-2',
  evalSectionHead: 'flex items-baseline gap-3',
  evalTierHead: 'flex gap-2 [margin-bottom:var(--space-1)]',
  evalTierSection: '[margin-top:var(--space-3)]',
  evalTierSub: '',
  feedback: '[margin-top:var(--space-3)] flex',
  finRunbookMsg: '[margin-top:var(--space-3)]',
  gapBars: 'text-muted-foreground',
  gapBarsLow: 'text-muted-foreground font-bold',
  gapCheckbox: '',
  gapColCheck: '[padding-left:var(--space-2)] [padding-right:var(--space-2)]',
  gapDate: 'text-muted-foreground',
  gapReason: 'text-muted-foreground',
  gapReasonCount: 'font-bold text-muted-foreground',
  gapReasonLabel: 'text-muted-foreground',
  gapReasonPill: 'inline-flex p-[0.2rem var(--space-2)] rounded-[6px] border border-border',
  gapRowSelected: '',
  gapShowMore: '',
  gapSymbol: 'font-bold text-muted-foreground',
  gapTable: 'w-full border-collapse',
  infoBanner: 'border border-border rounded-[8px] [margin-bottom:var(--space-4)] text-muted-foreground',
  infoTab: 'border border-border text-muted-foreground rounded-[999px] p-[0.4rem 0.85re] font-bold',
  infoTabActive: 'text-muted-foreground',
  infoTabs: 'inline-flex gap-2',
  inventoryCategory: 'inline-flex font-semibold rounded-[4px] bg-card border border-border',
  inventoryCategoryCashflow: 'text-muted-foreground',
  inventoryCategoryQuality: 'text-muted-foreground',
  inventoryCategoryShort: 'text-muted-foreground',
  inventoryCategoryValuation: 'text-muted-foreground',
  inventoryFillBar: 'rounded-[3px] bg-card shrink-0',
  inventoryFillBarInner: 'rounded-[3px]',
  inventoryFillBarInnerErr: 'rounded-[3px]',
  inventoryFillBarInnerOk: 'rounded-[3px]',
  inventoryFillBarInnerWarn: 'rounded-[3px]',
  inventoryFillPct: 'tabular-nums text-muted-foreground',
  inventoryFillWrap: 'flex gap-2',
  inventoryIndicator: 'text-muted-foreground',
  inventoryTable: 'w-full border-collapse [margin-top:var(--space-2)]',
  inventoryTableName: 'text-muted-foreground',
  maintenanceBadge: 'shrink-0 font-extrabold uppercase rounded-[3px] [margin-top:0.1e]',
  maintenanceBadgeAuto: 'text-muted-foreground',
  maintenanceBadgeManual: 'shrink-0 font-extrabold uppercase rounded-[3px] [margin-top:0.1e]',
  maintenanceBox: 'border border-border rounded-[6px] flex gap-2',
  maintenanceBoxTitle: 'font-bold uppercase text-muted-foreground [margin-bottom:0.1re]',
  maintenanceRow: 'flex gap-2 text-muted-foreground',
  maintenanceText: '',
  metric: 'bg-card border border-border rounded-[10px] flex',
  metricLabel: 'text-muted-foreground font-semibold uppercase',
  metricSub: 'text-muted-foreground [margin-top:0.1re]',
  metricValue: 'font-bold text-muted-foreground',
  metricValueAccent: 'text-muted-foreground',
  metricsStrip: 'grid gap-3 [margin-bottom:var(--space-5)]',
  msgErr: 'text-muted-foreground',
  msgInfo: 'text-muted-foreground',
  msgOk: 'text-muted-foreground',
  optionEodStage: '',
  quickNav: 'flex gap-2 [padding-top:var(--space-4)] [margin-top:var(--space-4)]',
  readinessHealth: 'bg-card rounded-[6px] border border-border [margin-bottom:var(--space-4)]',
  readinessHealthBtns: 'flex gap-2 [margin-left:au]',
  readinessHealthRow: 'flex gap-2',
  readinessStatusActions: 'flex gap-2 [margin-left:au]',
  readinessStatusCard: '[margin-top:var(--space-4)]',
  readinessStatusHeader: 'flex gap-3 [margin-bottom:var(--space-3)]',
  readinessStatusTitle: 'font-semibold text-muted-foreground uppercase',
  resultContent: '',
  resultEntry: '',
  resultEntryChecked: '',
  resultEntryHeading: 'flex gap-2 [margin-bottom:0.2re]',
  resultEntryName: 'font-semibold text-muted-foreground flex-1 min-w-0',
  resultEntryNum: 'rounded-full border border-border inline-flex font-bold shrink-0 text-muted-foreground',
  resultIdle: 'text-muted-foreground [padding-left:calc(1.4rem + var(--space-2))] flex',
  resultsHeader: 'flex [padding-bottom:var(--space-2)] [margin-bottom:var(--space-2)]',
  resultsList: 'flex',
  resultsListStaged: 'gap-3',
  resultsResetBtn: 'border border-border rounded-[3px] text-muted-foreground',
  resultsStage: 'rounded-[10px]',
  resultsStageChevron: 'text-muted-foreground [margin-left:var(--space-1)] shrink-0',
  resultsStageCount: 'text-muted-foreground shrink-0',
  resultsStageEntries: '',
  resultsStageHead: 'flex gap-2 [margin-bottom:var(--space-1)]',
  resultsStageTitle: 'flex-1 min-w-0 font-bold text-muted-foreground uppercase',
  resultsStageToggle: 'w-full border-0',
  resultsTitle: 'font-bold uppercase text-muted-foreground',
  runbookActionsHead: 'flex gap-3 [margin-bottom:var(--space-4)]',
  runbookLayout: 'grid gap-4',
  runbookMain: 'min-w-0 flex gap-3',
  runbookResults: 'min-w-0 border border-border rounded-[10px] flex',
  runbookStage: 'flex min-w-0 rounded-[10px]',
  runbookStageDone: 'flex min-w-0 rounded-[10px]',
  runbookStageOpen: 'flex min-w-0 rounded-[10px]',
  runbookStageBlurb: 'text-muted-foreground [margin-top:0.15re]',
  runbookStageBody: '',
  runbookStageHead: '',
  runbookStageHeadVoid: '',
  runbookStageHeadTop: 'flex gap-2 [margin-bottom:0.15re]',
  runbookStageKicker: 'font-extrabold uppercase text-muted-foreground',
  runbookStageProgress: '[margin-top:0.35re] text-muted-foreground',
  runbookStageSteps: 'flex flex-1',
  runbookStageSubtitle: '',
  runbookStageTitle: 'font-bold text-muted-foreground',
  runbookStageflow: 'grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 rounded-[12px] items-stretch',
  runbookTab: 'appearance-none border-0 text-muted-foreground grid gap-2 relative rounded-[9px]',
  runbookTabActive: 'text-muted-foreground',
  runbookTabDone: 'appearance-none border-0 text-muted-foreground grid gap-2 relative rounded-[9px]',
  runbookTabNested: 'rounded-[8px]',
  runbookTabIndex: 'rounded-[999px] inline-flex font-bold border border-border text-muted-foreground relative',
  runbookTabSub: 'text-muted-foreground',
  runbookTabText: 'min-w-0 flex',
  runbookTabTitle: 'font-bold',
  sectionCard: 'bg-card border border-border rounded-[10px] [margin-bottom:var(--space-4)]',
  sectionCardHeader: 'flex gap-3 [margin-bottom:var(--space-3)]',
  sectionCardTitle: 'font-bold text-muted-foreground m-0',
  sectionDivider: 'flex gap-3',
  sectionDividerLabel: 'font-bold uppercase text-muted-foreground',
  sectionDividerLine: 'flex-1',
  skeletonCard: 'bg-card border border-border rounded-[10px]',
  snapByTypeCode: '',
  snapByTypeLow: '',
  snapByTypeNum: 'tabular-nums',
  snapByTypeTable: 'w-full border-collapse',
  sourceAccent: 'absolute rounded-[10px]',
  sourceCard: 'bg-card border border-border rounded-[10px] flex relative',
  sourceDepends: 'flex [margin-top:0.15re]',
  sourceHeader: 'flex gap-2',
  sourceInner: 'flex gap-3 flex-1',
  sourceMeta: 'text-muted-foreground flex',
  sourceMetaKey: 'font-semibold uppercase text-muted-foreground',
  sourceMetaVal: 'text-muted-foreground',
  sourceObject: 'font-semibold text-muted-foreground',
  sourceRole: 'text-muted-foreground',
  sourceSchema: 'text-muted-foreground',
  sourceSqlBadge: 'inline-flex font-bold rounded-[3px]',
  sourceSqlBadgeOff: 'text-muted-foreground',
  sourceSqlCode: 'm-0',
  sourceSqlCopyBtn: 'shrink-0 font-semibold rounded-[4px]',
  sourceSqlCopyBtnOk: 'shrink-0 font-semibold rounded-[4px]',
  sourceSqlEmpty: '',
  sourceSqlPopover: 'absolute rounded-[8px]',
  sourceSqlPopoverHead: 'flex gap-2 [margin-bottom:0.35re]',
  sourceSqlPopoverTitle: 'font-bold uppercase [margin-bottom:0] flex-1 min-w-0',
  sourceTag: 'shrink-0 font-bold uppercase rounded-[3px]',
  sourceTagWrap: 'inline-flex shrink-0',
  sqlBlock: '',
  sqlBlockHead: 'flex gap-3',
  sqlBlockTitle: 'text-muted-foreground',
  sqlCode: 'text-muted-foreground m-0',
  sqlCopyBtn: 'inline-flex border border-border text-muted-foreground shrink-0',
  sqlCopyBtnCopied: 'text-muted-foreground',
  sqlLegend: 'flex gap-2',
  sqlLegendFormula: 'text-muted-foreground',
  sqlLegendLabel: 'text-muted-foreground',
  sqlLegendRow: 'grid gap-3 items-baseline',
  sqlLegendTitle: 'font-semibold text-muted-foreground [margin-bottom:var(--space-1)]',
  sqlPanel: '[margin-top:var(--space-3)] border border-border bg-card',
  sqlToggle: 'inline-flex gap-[3px] border border-border text-muted-foreground shrink-0',
  sqlToggleActive: 'text-muted-foreground',
  statusPill: '',
  statusPillErr: '',
  statusPillOk: '',
  statusPillWarn: '',
  step: 'grid relative',
  stepActive: 'grid relative',
  stepDone: 'grid relative',
  stepPanelActive: 'grid relative',
  stepPanelHidden: 'grid relative',
  stepActions: 'flex gap-2',
  stepAside: '[margin-top:var(--space-3)] bg-card border border-border rounded-[6px]',
  stepAsideDim: 'text-muted-foreground',
  stepAsideEmpty: '[margin-top:var(--space-3)] text-muted-foreground border border-border rounded-[6px]',
  stepAsideMeta: 'text-muted-foreground',
  stepAsideTableScroll: '',
  stepAsideTitle: 'font-semibold [margin-bottom:var(--space-2)] flex items-baseline gap-2',
  stepBody: '[padding-bottom:var(--space-4)] min-w-0',
  stepDesc: 'text-muted-foreground',
  stepHint: '',
  stepLabel: 'font-semibold text-muted-foreground m-0',
  stepList: 'flex',
  stepListPanel: 'rounded-[12px]',
  stepNum: 'rounded-full flex font-bold shrink-0 relative border border-border bg-card text-muted-foreground',
  stepTwinCard: 'rounded-[8px] flex gap-2',
  stepTwinGrid: 'grid gap-3',
  stepTwinTag: 'inline-flex p-[0.1rem 0.45re] rounded-[3px] font-bold uppercase',
  stepTwinTagHolidays: 'inline-flex p-[0.1rem 0.45re] rounded-[3px] font-bold uppercase',
  stepTwinTagTickers: 'inline-flex p-[0.1rem 0.45re] rounded-[3px] font-bold uppercase',
  stepTwinTitle: 'flex gap-2 text-muted-foreground font-semibold m-0',
  supportFundCell: 'flex min-w-0',
  supportFundCellAmount: 'text-muted-foreground',
  supportPill: 'font-bold border-0 p-0',
  supportPillNo: 'font-bold border-0 p-0',
  supportPillOk: 'font-bold border-0 p-0',
  supportPillPartial: 'font-bold border-0 p-0',
  supportPillUnknown: 'font-bold border-0 p-0',
  table: 'w-full border-collapse',
  tableCompact: 'w-full border-collapse',
  tableEmpty: 'text-muted-foreground',
  textDanger: '',
  textDim: '',
  textOk: '',
  textWarn: '',
  thStackedSub: 'block [margin-top:0.2re] font-medium uppercase text-muted-foreground',
  warnBanner: 'flex gap-3 rounded-[8px] [margin-bottom:var(--space-4)] text-muted-foreground',
} as const

/** Lookup with optional variant suffix e.g. `--ok` */
export function sdp(base: string, variant?: string) {
  const key = camel_case(base.replace(/^^sdp-/, "") + (variant ? `--${variant}` : ""))
  return (SDP as Record<string, string>)[key] ?? ""
}

function camel_case(s: string): string {
  const parts = s.split(/[-_]/)
  return parts[0] + parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("")
}

export function sdpcn(base: string, variant?: string, extra?: string) {
  return cn(sdp(base, variant), extra)
}
